### ISSUE TITLE
API calls not always updating permissions attribute

### ISSUE THREAD

**Issue by ldrbrandon** [plaid/plaid-ruby#100]
I'm not sure what the rules are when updating the permissions attribute in the user object but my flow is generally:

plaid_user = Plaid.set_user(access_token,[])
--> Plaid user object with blank attributes besides access_token

plaid_user.upgrade('connect')
--> Plaid user object with info from connect but permissions attribute remains an empty array

transactions = Plaid.transactions(plaid_user.access_token, account: plaid_user.accounts[0].id)
--> Plaid transactions array, plaid user object still shows permissions as an empty array

Is this a bug or am I doing something that is not properly updating the permissions?

**Comment by be9** [comment]
I'd suggest switching to 2.0.0.alpha which we've just released. This new version has another, simpler take on "permissions", replacing them with "current product" which is a single Symbol.

The 1.7.x version won't be fixed, so I'm closing this.
