### ISSUE TITLE
Increase the Net::ReadTimeout

### ISSUE THREAD

**Issue by Deekor** [plaid/plaid-ruby#103]
Some calls to the `Plaid.add_user` endpoint are timing out. Plaid support has informed me to set the timeout to at least 2 minutes. Is this something we can support here or should I fork?

http://stackoverflow.com/a/15158248/1094339

**Comment by peterb0yd** [comment]
Having this same issue all of a sudden. Must be a recent change or update to Plaid's API. Getting a solid 15 second benchmark for each "add_user" call in the console, and a timeout error in the app.

**Comment by Deekor** [comment]
I've submitted a pull request with a fix for this: https://github.com/plaid/plaid-ruby/pull/104

In the mean time feel free to use our fork: https://github.com/TaxAlli/plaid-ruby

**Comment by be9** [comment]
The issue has been resolved in 2.0.0.alpha as I described in #104.

Closing this.
