### ISSUE TITLE
undefined method `client_id=' for Plaid:Module (NoMethodError)

### ISSUE THREAD

**Issue by satendra-dhillon** [plaid/plaid-ruby#119]
I've added a filed named 'plaid.rb' in config/initializers.
and added the code with updated configuration i.e. client_id and secret-

Plaid.config do |p|
  p.client_id = '<<< Plaid provided client ID >>>'
  p.secret = '<<< Plaid provided secret key >>>'
  p.env = :tartan  # or :api for production
end

It is showing the error "undefined method `client_id=' for Plaid:Module (NoMethodError)" on statting the server.

**Comment by be9** [comment]
@satendra-dhillon Are you sure you are using the latest version of the gem, 2.0.0? The previous version, 1.7.1, was configured in a slightly different manner.

**Comment by satendra-dhillon** [comment]
Thanks @be9 . Now it works.

**Comment by michaelckelly** [comment]
@satendra-dhillon -

> Is there any way to manage the bank account with plaid API like add/edit or delete?

You can delete your access to an entire access token by using `Plaid::User.delete`.

**Comment by satendra-dhillon** [comment]
@michaelckelly 
Thanks

**Comment by satendra-dhillon** [comment]
@michaelckelly 

Ok, Thanks.

**Comment by be9** [comment]
@satendra-dhillon I hope everything works for you now. Closing this.
