### ISSUE TITLE
Configuration instructions are incorrect

### ISSUE THREAD

**Issue by dankozlowski** [plaid/plaid-ruby#122]
The README dictates that the developer should create an initializer with the following:

```
Plaid.config do |p|
  p.client_id = '<<< Plaid provided client ID >>>'
  p.secret = '<<< Plaid provided secret key >>>'
  p.env = :tartan  # or :production
end
```

However, none of these attributes exist on the called configuration class:

```
# /usr/local/bundle/gems/plaid-1.7.1/lib/plaid/config.rb
module Plaid
  module Configure
    attr_accessor :customer_id, :secret, :environment_location

    KEYS = [:customer_id, :secret, :environment_location]

    def config
      yield self

      # Add trailing slash to api url if it is not present
      if self.environment_location[-1] != '/'
        self.environment_location += '/'
      end

      self
    end

  end
end
```

Any attempt to set these keys per the documentation leads to missing accessor errors, such as:

```
/code/config/initializers/plaid.rb:2:in `block in <top (required)>': undefined method `client_id=' for Plaid:Module (NoMethodError)
	from /usr/local/bundle/gems/plaid-1.7.1/lib/plaid/config.rb:8:in `config'
	from /code/config/initializers/plaid.rb:1:in `<top (required)>'
```

Here's my initializer:

```
# config/initializers/plaid.rb
Plaid.config do |p|
  p.client_id = ENV['PLAID_CLIENT_ID']
  p.secret    = ENV['PLAID_SECRET_KEY']

  if Rails.env.development? || Rails.env.test?
    p.env = :tartan
  else
    p.env = :production
  end
end
```

**Comment by dankozlowski** [comment]
Closed, was using older version.

**Comment by petergzli** [comment]
Hey @dankozlowski I'm experiencing the exact same issue.

I have:

require 'plaid'
Plaid.config do |p|
  p.client_id = ENV['PLAID_CLIENT_ID']
  p.secret = ENV['PLAID_SECRET']
  p.env = :tartan  # or :production
end

IN my init. But When I access or exchange link token, it breaks... Do you have any insights?

**Comment by be9** [comment]
@petergzli which gem version do you use?

**Comment by petergzli** [comment]
@be9 I'm on 3.0.0. The very latest version. 

If I set them in the same controller immediately before making the Plaid connection, it still returns as if I never set the variables... I double checked on rails console that I can indeed access the Env variables, and that is not the issue.

**Comment by be9** [comment]
@petergzli I'd need a stack trace to see what's going on.

**Comment by alirezaseifi** [comment]
I'm updating plaid from 1.7.1 to 4.0.0

# ./config/initializers/plaid.rb
```
Plaid.config do |p|
  p.client_id = ENV["PLAID_CUSTOMER_ID"]
  p.secret = ENV["PLAID_SECRET_KEY"]
  p.env = ENV["PLAID_URL"]
end
```
however I'm getting the following error

NoMethodError:
  undefined method `config' for Plaid:Module

**Comment by be9** [comment]
@alirezaseifi check https://github.com/plaid/plaid-ruby#creating-a-plaid-client

I'd also recommend using 5.0.0 version.
