### ISSUE TITLE
SSL Issue when attempting to upgrade plaid user

### ISSUE THREAD

**Issue by davemcorwin** [plaid/plaid-ruby#124]
```
> user.upgrade(:info)
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
from /Users/dcorwin/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
```

I am on a El Capitan and received this error with both openssl 0.9.8zh and 1.0.2h.

Brief googling reveals this may be an issue with the version of TLS or the cipher used by the server, but the bowels of encryption aren't really my cup o tea.

Thoughts? More details below:

```
plaid (2.0.0)
```

```
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
```

```
OpenSSL 1.0.2h  3 May 2016
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
```

**Comment by be9** [comment]
@dshvazz I can't reproduce this locally (El Capitan, openssl 0.9.8zh, ruby 2.2.3 built with rbenv).

Plaid's API servers only support TLS v1, 1.1 and 1.2. The error you posted shows an SSLv2/v3 connect attempt which should fail. But OpenSSL has an ability to negotiate, I wonder why it can't use any of TLS versions on your side.

**Comment by dshvazz** [comment]
Thats what I thought as well, not sure why this is happening. Note, this happened when i upgraded from 1.7.1 to 2.x, but 1.7.1 was using ssl, so i'm not sure what changed. I'll investigate a little more on my end to see if this is specific to my env.

**Comment by dshvazz** [comment]
@be9 Soooo, turns out that the problem as caused by setting the Plaid env to `'tartan'` instead of `:tartan`. Since we set these from environment variables ex `Plaid.config { |p| p.env = ENV['PLAID_ENV'] }` I assume strings are acceptable. I can symbolize here to address in the short term, but its generally a good idea for environment configuration to accept strings and possibly symbols, but not require symbols.

**Comment by dshvazz** [comment]
also, just noticed in my CI that if i don't pass anything i get `ArgumentError: Invalid value for Plaid::Client.env (:""): must be :tartan, :production, or a full URL, e.g. 'https://tartan.plaid.com'` perhaps if you are not going to allow strings for the env name, this could be included in this exception?

**Comment by be9** [comment]
@dshvazz we reserve String values for full URLs. If you look at the [code](https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/client.rb#L27), you'll see that we basically accept any String that is `URI.parse`-able. Unfortunately, one-word strings are parseable as well:

```
irb(main):002:0> URI.parse("tartan")
=> #<URI::Generic tartan>
```
I'm going to add more checks to ensure that the URL has scheme and host specified.

But you should still use `.to_sym`, I guess 😄

**Comment by edmundloo** [comment]
Major version bump invalidates issue.
