### ISSUE TITLE
Error in README under "Exchanging a Link public token for a Plaid access token"

### ISSUE THREAD

**Issue by secondstreetmedia** [plaid/plaid-ruby#125]
Currently, the code shown for using `User.exchange_token` with more options reads:

`user2 = Plaid::User.exchange_token('public_token', account_id: '...', product: :auth)`

But this throws an `unknown keyword: account_id` error.

The code that is working without error for me is:

`user2 = Plaid::User.exchange_token('public_token', 'account_id', product: :auth)`

**Comment by michaelckelly** [comment]
Thanks for raising this, @secondstreetmedia - I'll let @be9, the library maintainer, give the last sign off here!

**Comment by be9** [comment]
Thanks @secondstreetmedia, fixed.
