### ISSUE TITLE
check User#product in initializer

### ISSUE THREAD

**Issue by betesh** [plaid/plaid-ruby#132]
I might be wrong here, but it seems that `User#check_product` is not used thoroughly enough to ensure that the gem raises an error before passing an invalid product to the connector.

I suggest calling `check_product(product)` from `User#initialize` instead of `User.load`.

I'm waiting for feedback before starting a PR.

**Comment by be9** [comment]
As far as I see, all official ways to instantiate `Plaid::User` make this check. But I wouldn't object to a PR 👍

**Comment by betesh** [comment]
>  all official ways

Does that mean that `User.new` is not officially supported?

Is there a way to enforce that?  Perhaps `private_class_method :new`?

**Comment by be9** [comment]
> Does that mean that `User.new` is not officially supported?

Well, `def initialize` is marked as **Internal**. It's a mild suggestion to not create `User` instances by hand.

> Is there a way to enforce that? Perhaps `private_class_method :new`?

This would be the way. I never cared enough to close all the holes, but you could try to do it in your PR.

**Comment by betesh** [comment]
Alternatively, if we move `check_product` into `initialize`, `User.load` will be a thin wrapper around `User.new`:

    new product, access_token: token, client: client

so it seems fair to ask why `User.load` is even necessary.

If it's just to enforce that when the User is instantiated, it must have an `access_token`, either as a keyword attribute or in the `response`, then perhaps it would be better to raise an exception explicitly in such a case and get rid of the thin wrapper.

Once again, awaiting feedback before starting a PR.

**Comment by be9** [comment]
@betesh No, `User.load` stays as is. People code against this interface, after all.

I might reconsider when we at Plaid finally implement API v2 and I get to support it in gem 3.0.

**Comment by be9** [comment]
Closing for now. The current interface stays as is, and we think about better interfaces for API v2 (still in the works at Plaid!).
