### ISSUE TITLE
Retrieving the users balance.

### ISSUE THREAD

**Issue by jacobnbrum** [plaid/plaid-ruby#134]
Using plaid v 2.0.0

When I try a test call with the api to /connect it returns a response like this:

`{
  "accounts": [
    {
      "_id": "QP232464b5654b645OwK",
      "_item": "Kd2v3423423v4234rerfsdAA",
      "_user": "eJXp2dfverersberse55bRYa",
      "balance": {
        "available": 1203.42,
        "current": 1274.93
      },
      "institution_type": "fake_institution",
      "meta": {
        "name": "Plaid Savings",
        "number": "9606"
      },
      "subtype": "savings",
      "type": "depository"
    },
    {
      "_id": "nbvs3v234234232343vBMy",
      "_item": "KdDjmojBERUK2v34234v234234v234v3432AA",
      "_user": "eJXpM2c3423c423c34c32c4na0RYa",
      "balance": {
        "available": 1081.78,
        "current": 1253.32
      },
      "institution_type": "fake_institution",
      "meta": {
        "name": "Plaid Checking",
        "number": "1702"
      },
      "subtype": "checking",
      "type": "depository"
    }, ...` 

Which includes the balance. When I try making the same call with the plaid-ruby gem the response I receive does not contain a balance. Even when I try to update it by calling `plaid_user.balance` it just returns a list of the accounts without any balance information.  Calling `plaid_user.accounts` does not either return a balance. 

Am I doing something wrong, is this a bug, or is this the expected behavior. If this is the expected behavior is there a way that I could get the current balance using this gem?

Thank you!

**Comment by jacobnbrum** [comment]
I now see that the balance can be extracted from an account like `plaid_user.accounts.first.current_balance`, is there any reason why it is not visible in the accounts array?

**Comment by rubendinho** [comment]
As far as i understand the new version, doing `user.balance` or `user.income` makes the request and updates the object to have the corresponding information.  It's then up to you to call on the appropriate methods on user to get the data you need.

**Comment by jacobnbrum** [comment]
Right, but doesn't the connect call itself return a balance? Why should we need to make a balance request when this data is returned with connect itself?

**Comment by jacobnbrum** [comment]
So calling user.transactions makes the :connect request. Which actually does give you access to the accounts, balance, and transactions. Thanks
