### ISSUE TITLE
Can't delete Plaid user

### ISSUE THREAD

**Issue by SupremeA** [plaid/plaid-ruby#135]
I am using the 2.0.0 version of this gem and I keep getting the error `NoMethodError: undefined method "delete" for Plaid::User:Class` when I try to delete my user from plaid. The documentation is a little vague as there is no direct method in the readme showing how to delete but what am I missing?

My method is as follows:

     def destroy_plaid_account
        Plaid::User.delete
     end

I have also tried:

     def destroy_plaid_account
        Plaid::User.delete('connect',{access_token: self.access_token})
     end

**Comment by rubendinho** [comment]
You need to first load the user, then call the delete method on it. Like this: 

Plaid::User.load(:connect, self.access_token).delete

**Comment by SupremeA** [comment]
Yep, that was it, Thanks!

**Comment by rubendinho** [comment]
No problem glad that helped.
