### ISSUE TITLE
testing MFA on tartan

### ISSUE THREAD

**Issue by dam13n** [plaid/plaid-ruby#138]
`plaid_selections` doesn't seem to work for me as a username. I keep getting invalid credentials errors. `plaid_test` works fine.

**Comment by michaelckelly** [comment]
@dam13n - are you using type `citi`? Selections MFA is only available for Citi bank at this time.

**Comment by dam13n** [comment]
Thanks, looks like `citi` is working @michaelckelly ! I may have missed in the docs, but if it's not there, yall should add it! : )
