### ISSUE TITLE
testing error responses

### ISSUE THREAD

**Issue by dam13n** [plaid/plaid-ruby#142]
Whether an option on tartan or the gem (or both ideally), it'd be nice to simulate errors for endpoints. For example, I've already added an Institution successfully, then the credentials change or the account gets locked - I'd like to test for those 1XXX codes.

**Comment by be9** [comment]
I think this is achievable by using mocks (if in test mode) or the old-fashioned `alias_method_chain` trick to change stuff under Plaid namespace making it throw `Plaid::Error`s of different sorts.

Currently there are no plans to incorporate such functionality to the gem itself, sorry for that.
