### ISSUE TITLE
Instantiating a user with MFA questions

### ISSUE THREAD

**Issue by creaumond** [plaid/plaid-ruby#147]
Curious if there is any way to get MFA questions back after a user has been created. 

When I create a user that requires MFA questions with:
`user = Plaid::User.create(:connect, 'wells', 'plaid_test', 'plaid_good')`
I am unable to instantiate that user again to retrieve the MFA questions and submit the answer. 

When an MFA is required, I want to send the user to a form where they can answer the questions. As I move them to that form, I lose the "user" object. When I try to instantiate the user again with:
`example = Plaid::User.load(:connect, 'access_token')` I get the object, but I am unable to retrieve the questions and I see `@mfa_required=nil`. As I understand from the docs, this is likely because this is not actually making an API call.

Can I call something on "example" to get the questions back? Or does this all need to be completed on initial creation of the user object?

**Comment by be9** [comment]
@creaumond You can just call `example.mfa_step('answer to a question')` and it will work. The state is managed by Plaid backend, and you don't need questions in the object to make this call.

But if you need to access questions after the original `Plaid::User` object is lost, you'll have to store them somewhere, e.g. in a user session, in a cache, etc.

P.S. Sorry for late response. If you have any urgent questions, please do not hesitate to contact [Plaid support](https://plaid.com/contact/support/) which would respond in a much more timely fashion.

**Comment by edmundloo** [comment]
Major version bump invalidates issue.
