### ISSUE TITLE
Longtails name search, all not working on ruby

### ISSUE THREAD

**Issue by SupremeA** [plaid/plaid-ruby#148]
I tried to search a long tail institution name that was returned to me and I can't seem to get the API to find it. The institution came to me as "ins_105151" when I do the query as instructed     `Plaid::LongTailInstitution.search(query: 'ins_105151')`

I get a blank response.

Is this working? 

Also, I ran 

`Plaid::LongTailInstitution.all(count: 20, offset: 20)`
and got the response 
`TypeError: no implicit conversion of String into Integer`
Is there a printed list I can search for testing

**Comment by be9** [comment]
@SupremeA  try `Plaid::LongTailInstitution.get('ins_105151')`.

As for TypeError, could you also provide the stack trace?

**Comment by SupremeA** [comment]
`irb(main):005:0> Plaid::LongTailInstitution.all(count: 20, offset: 20)
TypeError: no implicit conversion of String into Integer
	from /app/vendor/bundle/ruby/2.2.0/gems/plaid-2.2.0/lib/plaid/institution.rb:143:in `[]'
	from /app/vendor/bundle/ruby/2.2.0/gems/plaid-2.2.0/lib/plaid/institution.rb:143:in `block in initialize'
	from /app/vendor/bundle/ruby/2.2.0/gems/plaid-2.2.0/lib/plaid/institution.rb:142:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/plaid-2.2.0/lib/plaid/institution.rb:142:in `initialize'
	from /app/vendor/bundle/ruby/2.2.0/gems/plaid-2.2.0/lib/plaid/institution.rb:215:in `new'
	from /app/vendor/bundle/ruby/2.2.0/gems/plaid-2.2.0/lib/plaid/institution.rb:215:in `block in all'
	from /app/vendor/bundle/ruby/2.2.0/gems/plaid-2.2.0/lib/plaid/institution.rb:215:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/plaid-2.2.0/lib/plaid/institution.rb:215:in `map'
	from /app/vendor/bundle/ruby/2.2.0/gems/plaid-2.2.0/lib/plaid/institution.rb:215:in `all'
	from (irb):5
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.0.10/lib/rails/commands/console.rb:90:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.0.10/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.0.10/lib/rails/commands.rb:62:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'`

**Comment by SupremeA** [comment]
@be9 Tried `Plaid::LongTailInstitution.get('ins_105151')` and got nil

**Comment by be9** [comment]
@SupremeA I encourage you to switch to using gem version 3.0.0 which uses the new Plaid backend institutions endpoint which kinda unites native and long-tail institutions. I've just ran your commands against 3.0.0:

```
[1] pry(main)> Plaid::Institution.all(count: 20, offset: 20)
=> [#<Plaid::Institution id="ins_100007", type="ins_100007", name="Simple">,
 #<Plaid::Institution id="ins_100008", type="ins_100008", name="Huntington Bank">,
 #<Plaid::Institution id="ins_100009", type="ins_100009", name="Barclaycard">,
 #<Plaid::Institution id="ins_100010", type="ins_100010", name="Fifth Third Bank">,
 #<Plaid::Institution id="ins_100013", type="ins_100013", name="M&T Bank">,
 #<Plaid::Institution id="ins_100024", type="ins_100024", name="BECU">,
 #<Plaid::Institution id="ins_100025", type="ins_100025", name="Schools First Federal Credit Union">,
 #<Plaid::Institution id="ins_100026", type="ins_100026", name="State Employees Credit Union">,
 #<Plaid::Institution id="ins_100030", type="ins_100030", name="Arvest Bank">,
 #<Plaid::Institution id="ins_100034", type="ins_100034", name="American Express Serve Prepaid Card">,
 #<Plaid::Institution id="ins_100036", type="ins_100036", name="Bluebird by American Express">,
 #<Plaid::Institution id="ins_100037", type="ins_100037", name="GoBank">,
 #<Plaid::Institution id="ins_100038", type="ins_100038", name="Webster Bank">,
 #<Plaid::Institution id="ins_100039", type="ins_100039", name="HR Block Emerald Card">,
 #<Plaid::Institution id="ins_100040", type="ins_100040", name="WalMart Prepaid MoneyCard">,
 #<Plaid::Institution id="ins_100041", type="ins_100041", name="Commerce Bank">,
 #<Plaid::Institution id="ins_100042", type="ins_100042", name="Redwood Credit Union">,
 #<Plaid::Institution id="ins_100043", type="ins_100043", name="First National Bank of Omaha">,
 #<Plaid::Institution id="ins_100044", type="ins_100044", name="San Diego County CU">,
 #<Plaid::Institution id="ins_100045", type="ins_100045", name="Randolph Brooks Federal Credit Union">]
[2] pry(main)> Plaid::Institution.get('ins_105151')
=> #<Plaid::Institution id="ins_105151", type="ins_105151", name="MB Financial Bank">
```

**Comment by SupremeA** [comment]
Thanks, that worked GREAT! Will this search find ANY bank name in longtail? or just some.

**Comment by edmundloo** [comment]
Major version bump invalidates issue.
