### ISSUE TITLE
Tests failing with 402 payment required

### ISSUE THREAD

**Issue by j4ustin** [plaid/plaid-ruby#15]
1) Plaid Customer calls mfa_step and returns a response code of 200
    Failure/Error: new_account = Plaid.customer.mfa_auth_step('test','again','chase')
    
    RestClient::PaymentRequired: 402 Payment Required

**Comment by j4ustin** [comment]
@brian-vogogo 
We've released a new version of the gem, 1.0.1. These issues are now fixed on that version.

**Comment by brian-vogogo** [comment]
Awesome, thanks!

**Comment by j4ustin** [comment]
No problem, sorry for the long delay in closing this issue. This gem will be much more active from here on out.
