### ISSUE TITLE
Wrong PlaidError#new signature size

### ISSUE THREAD

**Issue by bobbywilson0** [plaid/plaid-ruby#159]
https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/connect.rb#L47

**Comment by bobbywilson0** [comment]
Raises expects 5 got 3 arguments error

**Comment by edmundloo** [comment]
Great catch! Will send out a PR to fix the issue! Thanks a ton for reporting!

**Comment by edmundloo** [comment]
PR to handle the issue is here: https://github.com/plaid/plaid-ruby/pull/161
Move conversation to the PR thread.
