### ISSUE TITLE
Is there a Plaid test client_id and secret?

### ISSUE THREAD

**Issue by stephenarifin** [plaid/plaid-ruby#163]
Hello, I am trying to test the exchange endpoint with link and I am getting this error:

**provided public token is an invalid format. expected format: public-<environment>-<identifier>**

I think it is because I am using my real client_id and secret, but I cannot find where the test client_id and secret are for sandbox environment. 

If I try using "test_id" and "test_secret" for client_id and secret, it gives me this error:

**client_id must be a properly formatted, non-empty string**

Also, the link https://plaid.com/docs/api/blob/master/SANDBOX.md is broken.

Thanks!

**Comment by michaelckelly** [comment]
@stephenarifin - You'll want to use your Plaid API keys that are available from the [Dashboard](https://dashboard.plaid.com/account/keys). The dummy `test_id` and `test_secret` API keys and have been deprecated for our new API!

**Comment by michaelckelly** [comment]
And thanks for the typo catch - fixed in #165!

**Comment by stephenarifin** [comment]
Wait sorry, I wasn't done yet. I am using the link v2 from your website and it is still giving me issues. Apparently I am using an outdated version of your link component, but I am pulling it straight from your source, which is listed on your website.

<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>

I am using the client_id and secret that was given to my account, but I am still receiving the same error messages.

**Comment by michaelckelly** [comment]
@stephenarifin - Initialize Link with the `apiVersion` flag set to `v2`!

**Comment by coopernewby** [comment]
If test_id and test_secret are deprecated are the test secret/id and prod secret/id the same? does the environment decide if it is billed for or pushed to the dev api?
