### ISSUE TITLE
Getting institution_id from account product

### ISSUE THREAD

**Issue by stephenarifin** [plaid/plaid-ruby#166]
Hey guys,

I'm using the sandbox environment and I am accessing the accounts endpoint. I was wondering if it was possible to get the institution_id associated with an account.

The docs here show we can get the institution_id but my response does not contain the institution_id. https://plaid.com/docs/api/#accounts

My code looks like this:

    response = $plaid_client.accounts.balance.get(self.access_token)

**Comment by edmundloo** [comment]
Hey @stephenarifin,

I've replicated your function call using sandbox credentials as well. I get the JSON as shown below. You can see that the institution_id is located under json[item][institution_id]. Can you confirm that you get a similar response? If not, could you please show us what you're getting from the sandbox API?

`{
  "accounts"=>[
    {
      "account_id"=>"XXXXX",
      "balances"=>{
        "available"=>100,
        "current"=>110,
        "limit"=>nil
      },
      "mask"=>"XXXX",
      "name"=>"Plaid Checking",
      "official_name"=>"Plaid Gold Standard 0% Interest Checking",
      "subtype"=>"checking",
      "type"=>"depository"
    },
    {
      "account_id"=>"XXXXX",
      "balances"=>{
        "available"=>200,
        "current"=>210,
        "limit"=>nil
      },
      "mask"=>"XXXX",
      "name"=>"Plaid Saving",
      "official_name"=>"Plaid Silver Standard 0.1% Interest Saving",
      "subtype"=>"savings",
      "type"=>"depository"
    },
    {
      "account_id"=>"XXXXX",
      "balances"=>{
        "available"=>nil,
        "current"=>1000,
        "limit"=>nil
      },
      "mask"=>"XXXX",
      "name"=>"Plaid CD",
      "official_name"=>"Plaid Bronze Standard 0.2% Interest CD",
      "subtype"=>"cd",
      "type"=>"depository"
    },
    {
      "account_id"=>"XXXXX",
      "balances"=>{
        "available"=>nil,
        "current"=>410,
        "limit"=>2000
      },
      "mask"=>"XXXX",
      "name"=>"Plaid Credit Card",
      "official_name"=>"Plaid Diamond 12.5% APR Interest Credit Card",
      "subtype"=>"credit",
      "type"=>"credit"
    }
  ],
  "item"=>{
    "available_products"=>[
      "auth",
      "balance",
      "credit_details",
      "identity"
    ],
    "billed_products"=>[
      "transactions"
    ],
    "error"=>nil,
    "institution_id"=>"ins_109508",
    "item_id"=>"XXXXX",
    "webhook"=>""
  },
  "request_id"=>"XXXXX"
}`
