### ISSUE TITLE
Client ID is only authorized to use Plaid Link

### ISSUE THREAD

**Issue by jasoncharnes** [plaid/plaid-ruby#168]
1. Thank you for this gem, it's fantastic.
2. I'm trying to contribute to `credit_details`. When I run `rake test` I get the following error: `your client ID is only authorized to use Plaid Link`

Is there another set of API credentials I should be using to run tests?

**Comment by michaelckelly** [comment]
@jasoncharnes - Thanks for opening up this issue and appreciate the contribution -- apologies for the difficulty with test runs. Try opening up a pull request from a fork of this repository, which should trigger a CI run. We're working to resolve this issue more completely in a future release, too!

**Comment by jasoncharnes** [comment]
@michaelckelly no worries at all! I'll open up the PR now. If there are any failing tests with CI, then I'll just keep pushing to the branch to trigger the suite. (Sorry in advance if I have to run multiple times and you get emails 😄 )

Thanks for the quick reply!
