### ISSUE TITLE
Testing the Income API in sandbox mode

### ISSUE THREAD

**Issue by theJman** [plaid/plaid-ruby#170]
Hi,

I'm working on a project that is using your income api in sandbox mode to pull data and I'm running into an issue when writing tests. When trying to access the income we are getting the error PRODUCT_NOT_READY. The solution to this on production is to provide a webhook but I was wondering if there are any other solutions that would work when running tests from localhost? 
Are there plans to make it so that a webhook isn't needed in sandbox? This would be a major help for people that are also using your api to test.

Thanks,
Jeremy

Here is the full error:
`
Failure/Error: response = $plaid_client.income.get(self.access_token)

     Plaid::ItemError:

       Error Type      : ITEM_ERROR
       Error Code      : PRODUCT_NOT_READY
       Error Message   : the requested product is not yet ready. please provide a webhook or try the request again later
       Display Message :
       Request ID      : 6frEx
`

**Comment by michaelckelly** [comment]
@theJman - Thanks for the question. The `PRODUCT_NOT_READY` error indicates that our system has not yet finished processing Income data for the Item. There is time required for this processing even in our Sandbox API environment (our goal is to make the Sandbox as representative of a Production integration as possible).

For building Income tests, you may want to simple write tests to validate that Income is listed as a billed product from the `item.get` method.
