### ISSUE TITLE
Cancel transactions webhook

### ISSUE THREAD

**Issue by stephenarifin** [plaid/plaid-ruby#178]
Hello,

Is there a way to disable the transaction normal update webhook? I want to just pull the transactions once and not have continual updates. I don't want to delete the entire item, just disable the updates.

I saw in the ruby library that there is a transaction disable method within the transaction class. I tried using that but it returned that the url path no longer exists.

Thanks,
Stephen

**Comment by rubendinho** [comment]
Could you not replace the webhook for that item with something bogus or blank?

**Comment by stephenarifin** [comment]
Seems like a very hacky way to deal with it. Just wanted to let the github know that the transactions disable endpoint is deprecated.
