### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by danielma** [plaid/plaid-ruby#182]
:wave:

https://github.com/plaid/plaid-ruby/pull/161 fixed an `ArgumentError` bug where `lib/plaid/connect.rb` attempted to create a `PlaidError` with the wrong number of arguments.

Since that bug has been fixed, would you consider publishing a new release to rubygems with that fix?

**Comment by be9** [comment]
@danielma 4.1.0 was released recently and we are prepping for 5.0.0.
