### ISSUE TITLE
NoMethodError: undefined method `to_sym' for nil:NilClass 

### ISSUE THREAD

**Issue by vadimivymark** [plaid/plaid-ruby#186]
i'm using Rails 4.2.8 and latest plaid gem
when trying to setup db for testing by: 

bundle exec rake db:schema:load RAILS_ENV=test, 

getting this error: 

NoMethodError: undefined method `to_sym' for nil:NilClass
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/plaid-5.0.0/lib/plaid/client.rb:21:in `initialize'
/home/ubuntu/Ivy-rails/config/initializers/plaid.rb:1:in `new'
/home/ubuntu/Ivy-rails/config/initializers/plaid.rb:1:in `<top (required)>'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/home/ubuntu/Ivy-rails/config/environment.rb:5:in `<top (required)>'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/ubuntu/Ivy-rails/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/opt/circleci/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/opt/circleci/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
/opt/circleci/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
/opt/circleci/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/opt/circleci/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by JPaulMora** [comment]
hi, could you please share how to solve this issue?

**Comment by sixcupsofcoffee** [comment]
Same. This issue was closed but I'm still getting the NoMethodError for `to_sym`.

**Comment by cherniv** [comment]
as a workaround just set all env vars directly in app.rb on lines 10-13
