### ISSUE TITLE
Sandbox webhooks don't work

### ISSUE THREAD

**Issue by sarink** [plaid/plaid-ruby#188]
After successfully creating a plaid item and registering a webhook, no `"INITIAL_UPDATE"` or `"HISTORICAL_UPDATE"` webhooks are ever fired, contradictory to what this documentation shows https://support.plaid.com/customer/en/portal/articles/2531035-testing-webhooks

When I create the product via `PlaidLink`, I use `products: ['transactions']` but I noticed when the webhook comes back that the item has `available_products: ['auth', 'identity']` and `billed_products: ['transactions']` - I'm not sure what that means but it seemed like it could be relevant.

My codes:
```
# plaid_items_controller.rb
  # POST /plaid_items
  def create
    exchange_token_response = PlaidItemsHelper.plaid_client.item.public_token.exchange(params[:public_token])
    access_token = exchange_token_response["access_token"]
    @plaid_item = PlaidItem.find_or_initialize_by({
      plaid_item_id: exchange_token_response["item_id"],
      access_token: access_token,
      request_id: exchange_token_response["request_id"],
      user: current_user,
      institution_id: params[:institution][:id],
      institution_name: params[:institution][:name],
    })
    if @plaid_item.save
      @plaid_item.register_webhooks
      render json: @plaid_item, status: :created, location: @plaid_item
    else
      render json: @plaid_item.errors, status: :unprocessable_entity
    end
  end

  # POST /plaid_items/webhook
  def webhook
    puts params
    # outputs: { "webhook_code": "WEBHOOK_UPDATE_ACKNOWLEDGED" ... }
    # no other webhook is ever triggered
  end
```
```
# plaid_item.rb
  def register_webhooks
    url = Rails.application.routes.url_helpers.plaid_items_webhook_url
    PlaidItemsHelper.plaid_client.item.webhook.update(self.access_token, url)
  end
```
```
# plaid_items_helper.rb
module PlaidItemsHelper
  def self.plaid_client
    Plaid::Client.new(
      env: :sandbox
      client_id: plaid_client_id
      secret: plaid_secret
      public_key: plaid_public_key
    )
  end
```

**Comment by michaelckelly** [comment]
@sarink - Please make sure you are initializing Link client side with the webhook you wish to use:

```html
<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js">
</script>
<script>
// Initialize Link with the `token` parameter
// set to the generated public_token for the Item
var linkHandler = Plaid.create({
  env: 'sandbox',
  clientName: 'Client Name',
  key: '[PUBLIC_KEY]',
  webhook: '[YOUR WEBHOOK URL]',
  product: ['transactions'],
  onSuccess: function(public_token, metadata) {
  },
  onExit: function(err, metadata) {
  },
});
// Trigger Link
document.getElementById('linkButton').onclick = function() {
  linkHandler.open();
};
</script>
```

If you do not include the webhook when initializing Link, you will not receive `INITIAL_UPDATE` and `HISTORICAL_UPDATE` transactions webhooks.

**Comment by sarink** [comment]
Ahh, I see! Thanks @michaelckelly

**Comment by exls** [comment]
I use same idea, but I update item webhook via api and I don't get the INITAL_UPDATE and HISTORICAL_UPDATE. Why?

Also. what is the behavior should be in case I set webhook in web js? What if webhokk request will come before the my request to my server with publicToken? Or first webhook comes after exchnageToken method?

**Comment by ravindart2011** [comment]
> @sarink - Please make sure you are initializing Link client side with the webhook you wish to use:
> 
> ```
> <script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js">
> </script>
> <script>
> // Initialize Link with the `token` parameter
> // set to the generated public_token for the Item
> var linkHandler = Plaid.create({
>   env: 'sandbox',
>   clientName: 'Client Name',
>   key: '[PUBLIC_KEY]',
>   webhook: '[YOUR WEBHOOK URL]',
>   product: ['transactions'],
>   onSuccess: function(public_token, metadata) {
>   },
>   onExit: function(err, metadata) {
>   },
> });
> // Trigger Link
> document.getElementById('linkButton').onclick = function() {
>   linkHandler.open();
> };
> </script>
> ```
> 
> If you do not include the webhook when initializing Link, you will not receive `INITIAL_UPDATE` and `HISTORICAL_UPDATE` transactions webhooks.

Hi  michaelckelly .
 how integrate webhook  in rails, I am impletementing plaid . what is webhook url ?

**Comment by ravindart2011** [comment]
> > @sarink - Please make sure you are initializing Link client side with the webhook you wish to use:
> > ```
> > <script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js">
> > </script>
> > <script>
> > // Initialize Link with the `token` parameter
> > // set to the generated public_token for the Item
> > var linkHandler = Plaid.create({
> >   env: 'sandbox',
> >   clientName: 'Client Name',
> >   key: '[PUBLIC_KEY]',
> >   webhook: '[YOUR WEBHOOK URL]',
> >   product: ['transactions'],
> >   onSuccess: function(public_token, metadata) {
> >   },
> >   onExit: function(err, metadata) {
> >   },
> > });
> > // Trigger Link
> > document.getElementById('linkButton').onclick = function() {
> >   linkHandler.open();
> > };
> > </script>
> > ```
> > 
> > 
> > If you do not include the webhook when initializing Link, you will not receive `INITIAL_UPDATE` and `HISTORICAL_UPDATE` transactions webhooks.
> 
> Hi michaelckelly .
> how integrate webhook in rails, I am impletementing plaid . what is webhook url ?

my application runing using ngrok  server , but
