### ISSUE TITLE
 undefined method `config' for Plaid:Module

### ISSUE THREAD

**Issue by alirezaseifi** [plaid/plaid-ruby#190]
I'm upgrading plaid from `1.7.1` to `4.0.0`

`# /config/initializers/plaid.rb`
```
Plaid.config do |p|
  p.client_id = ENV["PLAID_CUSTOMER_ID"]
  p.secret = ENV["PLAID_SECRET_KEY"]
  p.env = ENV["PLAID_URL"]
end
```
however I'm getting the following error
```
NoMethodError:
  undefined method `config' for Plaid:Module
```

**Comment by javierjulio** [comment]
@alirezaseifi how you configure the client has changed. Here is the example for v4: https://github.com/plaid/plaid-ruby/tree/v4.0.0#creating-a-plaid-client
