### ISSUE TITLE
Is `item/create`, `item/mfa` included in the deprecation plan of Sept. 30, 2018?

### ISSUE THREAD

**Issue by cabello** [plaid/plaid-ruby#196]
I am having a hard time finding docs for these two endpoints `POST /item/create` and `POST /item/mfa`, I see them implemented in the codebase:

https://github.com/plaid/plaid-ruby/blob/c870b7344c2facb9e046e9160582536fdaefe641/lib/plaid/products/item.rb#L193-L216

And:

https://github.com/plaid/plaid-ruby/blob/c870b7344c2facb9e046e9160582536fdaefe641/lib/plaid/products/item.rb#L296-L306

Are they included in the legacy API deprecation plan that will happen in September 30, 2018?

The reason I ask is because while cleaning up code I thought we were 100% on Plaid Link but after removing the legacy integration I found a few use cases using it, so I am posed with the following:
- Revert my changes, continue using this API for these cases
- Migrate these cases to Plaid Link somehow, does Plaid Link support *all* institutions?

Thanks!

**Comment by r-ohan** [comment]
Hi @cabello ! Thanks for writing in. In APIv2, Plaid Link is the only way to create items, you will need to migrate these cases to Plaid Link (it does support all institutions). If you have any further questions please write to support: https://dashboard.plaid.com/support.

**Comment by cabello** [comment]
Hi @r-ohan ! 
1. What's APIv2? Plaid website there is only 2018-05-22 and 2017-03-01
2. Are you removing these method calls soon or not?

**Comment by r-ohan** [comment]
Hi @cabello!
1. We introduced a new version of the API on 2017-03-08 that we sometimes refer to as APIv2. (v1 is the legacy API being deprecated in September). We've introduced a way to make minor breaking changes within APIv2 (https://plaid.com/docs/api-upgrades/), those "versions" are the dates you are seeing in the documentation.
2. These method calls can be used in sandbox to help with writing integration tests, but Plaid Link is the only way to create items in the Production environment.

Please write in to support if you have any further questions! https://dashboard.plaid.com/support.
