### ISSUE TITLE
0.1.6 not published

### ISSUE THREAD

**Issue by roykolak** [plaid/plaid-ruby#20]
Not sure if you are aware, but version 0.1.6 is not published and all the documentation in the README is related to this version. Was confusing trying to integrate. Also, version tags would be really helpful.

**Comment by j4ustin** [comment]
Hi @roykolak,

I've updated the rubygems version to 0.1.6. We're actually building a version 0.2 of this gem that has lots of improvements over the current version and should make integrating much easier. Expect this change this weekend!
