### ISSUE TITLE
add options param to institutions.get_by_id method

### ISSUE THREAD

**Issue by psloomis** [plaid/plaid-ruby#202]
There is currently a method to get institutions by ID, but it doesn't pass an `options` param in the request:

https://github.com/plaid/plaid-ruby/blob/8c681204bca82984ec4aa06f26732745d45d7642/lib/plaid/products/institutions.rb#L32-L35

I think this method should pass an `options` param so that users can make client requests like this:
```ruby
client.institutions.get_by_id(institution_id, options: { include_display_data: true })
```

Then the `get_by_id` method would pass the options in the request like this:
```ruby
    def get_by_id(institution_id, options: {})
      post_with_public_key 'institutions/get_by_id',
                           SingleInstitutionResponse,
                           institution_id: institution_id,
                           options: options
    end
```

Also, I would like to make a PR for this but don't have write access to the repo. How do I get write access?

**Comment by javierjulio** [comment]
@psloomis you don't need write access to the repo. Just fork this repo and create a branch using your fork. From there you'll be able to submit a PR here easily.
