### ISSUE TITLE
Introduction of Item `status` breaks Plaid-ruby 5.0.0

### ISSUE THREAD

**Issue by wallace** [plaid/plaid-ruby#215]
Hi all,

We experienced a new error starting yesterday in our production application.

`NoMethodError (The property 'status' is not defined for Plaid::Item::GetResponse.):`

I believe this is related to the new functionality that was just released.

Thank you,
 Jonathan

**Comment by mattiskan** [comment]
Hi @wallace, thanks for reporting this; we've prioritized investigating the issue closer.

**Comment by mattiskan** [comment]
We have managed to confirm the issue in the case where `Plaid.relaxed_models` has been set explicitly to `false` — would you mind confirming that this matches your situation?

In the very short term setting `Plaid.relaxed_models = true` should resolve the issue, but we are also working on a fix which should be deployed to our systems soon.

@wallace thanks again for reporting this, and keep us updated.

**Comment by davidzhanghp** [comment]
we have fixed this for plaid-ruby 5.0.0 server-side
