### ISSUE TITLE
Logos option invalid: `include_institution_data`

### ISSUE THREAD

**Issue by rubendinho** [plaid/plaid-ruby#217]
I was playing with the new logos feature introduced in #207, and was getting errors: 
```
Plaid::InvalidRequestError: 
Error Type      : INVALID_REQUEST
Error Code      : UNKNOWN_FIELDS
Error Message   : the following fields are not recognized by this endpoint: options.include_institution_data
```

Per the specs in the PR, the option should be `include_institution_data`, but the [Plaid Docs](https://plaid.com/docs/#institution-overview) say it should be `include_optional_metadata`. 

I was able to make a valid request by modifying my request to use `include_optional_metadata`.

**Comment by davidzhanghp** [comment]
Hi @rubendinho.

I apologize for that. That flag was poorly named. We have since rectified the situation and changed it to use the right flag.
