### ISSUE TITLE
start/end dates of transaction (gte/lte)

### ISSUE THREAD

**Issue by suhpreme** [plaid/plaid-ruby#23]
The bank I am connected to is Chase. I have successfully connected an account and am getting 2 year's worth of transactional data. 

However, I am having difficulty filtering that to a start and end date. I put in a date object and the run is successful, but I keep only getting the whole 2 years worth of transactions.

**Comment by j4ustin** [comment]
I think this feature might be missing from the Gem. I'll update this tag and should have something out in the next few hours to fix that.

**Comment by suhpreme** [comment]
thanks justin

**Comment by dam13n** [comment]
Also, @j4ustin do you have a sample curl request you can provide that shows how to use the start and end dates? I put them in as a root param and under options, but they didn't seem to work?

Is this up-to-date?
https://github.com/plaid/support/blob/master/data-availability.md

**Comment by j4ustin** [comment]
@suhpreme @dam13n This is a tricky issue. Not super well documented in the original API. I'll round up a few accounts today, test, post the cURL request here, and finally update the gem.

**Comment by j4ustin** [comment]
@suhpreme @dam13n 

Sorry for the super long delay on this one. 

I've added the options hash to the add_user call. You should now be able to use start and end dates in your calls. I'm not closing this issue yet as I'm not satisfied with the tests for this specific issue.

It was just pushed up in the latest release to fix some other bugs, and didn't break any existing functionality.

**Comment by suhpreme** [comment]
Hey @j4ustin,

Thanks for the update. 

I updated the gem and tried testing it and still can't get it to work on Ruby. Perhaps I'm listing the "options" while getting transactions incorrectly? I have the snippet of my code below. As you can see, I'm creating an options hash, formatting it into a JSON string, then putting it under options. The call runs through but I'm not getting the filter I'm looking for. Thanks again!

optionsHash = {
			"start_date"=>"05/10/2014",
			"end_date"=>"06/10/2014"
		}

options = JSON.generate optionsHash;

connectOptions = {
	                "username"=>username,
			"password"=>password,
			"type"=>account_type,
			"options"=>options
		} 

userAccount = Plaid.post('connect',connectOptions);

**Comment by michaelckelly** [comment]
Hi @suhpreme--

If you're currently testing on the sandbox, the date filters will unfortunately not work -- they are supported only on live accounts on this time.  We are working to expand this to the sandbox but I don't have an exact timeline for that.  

If you're still having troubles with the date filters when using a live account, feel free to follow up here or in our [support repo](github.com/plaid/support).

**Comment by j4ustin** [comment]
@suhpreme Also, when testing as a live call you shouldn't need to format as json as the library should already format the options correctly.

It should be something like Plaid.add_user('username','password','pin',{options:'value'}).

This would fit with how the rest of the UI works for this library. Again, I won't be closing this until better test are in place that validate that behavior.

**Comment by suhpreme** [comment]
Thanks for the update @michaelckelly and @j4ustin .

Thanks for the tip Justin--it really made things a lot clearer. Unfortunately, I'm only testing on one card right now so I can't confirm whether add_user was indeed able to filter the transactions. Couple things:

1) Seems like I'm not able to simply update transactions for a new user. The get_connect user method does not take in an the options hash to filter dates. I feel like there should be an "update_user" module that takes in options for start/end date to accommodate for this. Sorry if something like this has not been implemented yet, but am I just missing something here?
2) I decided to try a workaround and send my own POST to a /connect/get to test for transaction filters, and did not have any luck. The run was successful, but once again I got the full 2 years worth of transactions. For reference, here is the code below:

		print Plaid.post("connect/get", {"access_token"=>access_token, "gte"=>"05/10/2014","lte"=>"06/10/2014"})
		print Plaid.post("connect/get", {"access_token"=>access_token, "gte"=>Date.new(2015,1,25),"lte"=>Date.new(2015,1,30)});

Thank you guys again.

**Comment by dam13n** [comment]
Hey @suhpreme,

I just started integrating this, and it does work. You need to move the "gte" and "lte" in an "options" hash and do a POST on "connect/get". The Plaid docs look up to date and reflect this. 

I'm not sure if the new gem version supports this or not, but I'll be updating my fork of the previous version if you want to use it. When I get some time soon, I'll migrate to the new gem version and make sure it's working.

**Comment by dam13n** [comment]
The "start_date" and "end_date" for the GET request are working too. : D 

Thanks much @j4ustin and @michaelckelly

**Comment by j4ustin** [comment]
@dam13n @michaelckelly @suhpreme 

This will go into the next patch of the gem with full support added to the docs and wiki. I've added a milestone.

**Comment by michaelckelly** [comment]
Thanks for staying on top of this @j4ustin.  We'll try to be more proactive about messaging updates/new features for the sandbox in future!  

But yes, to reiterate, the sandbox supports filtering by account and date (lte & gte) now!

**Comment by suhpreme** [comment]
@j4ustin @michaelckelly @dam13n 

thanks for keeping up with this. i'm close to the point where I want to incorporate this in so the timing couldnt be better. if you are ever find yourself in NOLA, let me get you men a beer ;)

**Comment by j4ustin** [comment]
@dam13n With the latest version of the gem (1.3) you'll be able to use the ***Plaid.add_user*** or ***Plaid::User#get_connect*** to specify start and end dates of the transactions. 

Ex)

```ruby
 user = Plaid.add_user('connect','plaid_test','plaid_good','wells',"{'gte':'05/10/2014' , 'lte':'06/10/2014'}")
``` 

or

```ruby
 user = Plaid.get_connect("{'gte':'05/10/2014' , 'lte':'06/10/2014'}")
``` 
@suhpreme I'll be in NOLA in April and will take you up on that offer!
