### ISSUE TITLE
Faraday::SSLError

### ISSUE THREAD

**Issue by bonafernando** [plaid/plaid-ruby#232]
Sometimes we are receiving `Faraday::SSLError` on `plaid.transactions.get` method.

I would like to create a PR to catch that error and raise as a Plaid::PlaidAPIError.
I would like opinion of the team on where and how to do it to be able to create a time estimation to approve with my client.
With a quick search I got to the base where `Faraday` connection is called:
https://github.com/plaid/plaid-ruby/blob/66b86c510becbb2b6cf46e3931c37f39eb23766a/lib/plaid/client.rb#L116

Also, I think that not everyone would like to receive SSL errors as Plaid::PlaidAPIError, so I thought of a config variable to make it happen.

The reason I need this is because my `PlaidEventJob` worker already have a rescuer for `Plaid::PlaidAPIError`:
```
rescue_from(Plaid::PlaidAPIError) do |exception|
  retry_job(wait: 5.minutes) if exception.error_type == 'RATE_LIMIT_EXCEEDED'
end
```
I think it's better to treat it as a `Plaid::PlaidAPIError` than creating another mechanism to retry with limiter and etc, for this kind of errors. What do you think?

Thanks,
Fernando.

**Comment by davidzhanghp** [comment]
Hi Fernando,

I really appreciate your feedback on this issue.

We should not obsfucate SSL errors as PlaidApiErrors. The inability to connect or negotiate TLS/SSL should be treated separately from plaid api errors. 

While I understand that it may simplify error handling, it is in fact an unfortunate part of ruby that 1) SSL errors may be intermittent and difficult to predict 2) it can be hard to enumerate all the types of errors that may be emitted from a particular call.
