### ISSUE TITLE
Hashie 4.0 released

### ISSUE THREAD

**Issue by swrobel** [plaid/plaid-ruby#239]
Since you just require hashie >= apps will update to this version and there are potentially [breaking changes](https://github.com/intridea/hashie/pull/481). I don't see any ill effects, but just thought I'd point it out here for someone with knowledge of the code to check.

**Comment by skylarmb** [comment]
We are using 4.1.0 now: https://github.com/plaid/plaid-ruby/blob/master/Gemfile.lock#L18
