### ISSUE TITLE
Structure of Plaid.auth function is not consistent with the Plaid API

### ISSUE THREAD

**Issue by demosophy** [plaid/plaid-ruby#25]
'auth' has a specific meaning in the Plaid API similar to 'connect' - it denotes a level of API access: https://plaid.com/docs/?api-overview/#auth

Plaid.auth is more similar to the Plaid API 'add user' method under auth and connect.  Should we think about renaming this?  Or perhaps more appropriately, recreate auth to align with the auth API and do the same for connect?  

With the current structure there's no strait forward way (without using post) that I can see to submit get_connect or get_auth requests without resubmitting user credentials.

**Comment by dam13n** [comment]
I agree that some restructuring would be nice. You can use get_connect without resubmitting credentials if you have an access token already, but it's roundabout:

u = Plaid::User.new
u.access_token = 'test'
u.permissions = ['connect']

**Comment by j4ustin** [comment]
To solve this issue I believe renaming the auth flow to add_user makes the most sense. 

Once the user is added to Plaid one can simply use the Plaid::User.upgrade method to upgrade the user to both API levels. 

Or check Plaid::User.permissions for current levels, then use either the get_auth or get_connect methods to get the credentials again.

**Comment by j4ustin** [comment]
@dam13n @demosophy 

This has been updated the latest version of the gem (1.1.0).

**Comment by demosophy** [comment]
Awesome thanks!
