### ISSUE TITLE
webhook for MFA accounts

### ISSUE THREAD

**Issue by dam13n** [plaid/plaid-ruby#26]
Webhooks don't seem to work for MFA accounts (BofA / USAA) but do otherwise with the test credentials. Do I need to pass the webhook options for each response?

**Comment by j4ustin** [comment]
@dam13n WebHooks aren't built into the library yet. I'll add this in as an enhancement. Should be out in the same release as transaction settings.

**Comment by j4ustin** [comment]
@dam13n I've added the options hash to the add_user call. You should now be able to use webhooks in your calls. I'm not closing this issue yet as I'm not satisfied with the tests for this specific issue. 

It was just pushed up in the latest release to fix some other bugs, and didn't break any existing functionality.

**Comment by hosh** [comment]
+1 for webhooks

I also don't see complete documentation on webhooks in the API docs. I see what the "standard format" is, and the different kinds of webhook responses, but nothing on how to set it up, or the URL I can expect to be called after submitting a URL as a webhook.

If you guys have that kind of doc, I can submit a PR with the webhook code.

**Comment by ACPK** [comment]
+1.   Any progress on this as it's almost been a year.

**Comment by LucillaC** [comment]
@j4ustin I'm also curious if there has been any progress, I've been trying to implement web hooks and they do not appear to fire on any calls other than initial and historical transaction pulls

**Comment by j4ustin** [comment]
@apck @LucillaC, I am no longer a maintainer on this project in particular due to a massive job change I had that took over my duties. I let the team over at Plaid know about this way back in Q1 of this year. @michaelckelly might have more insight as to how feature requests can be made. 

Sorry for the trouble it may have caused.

**Comment by ldrbrandon** [comment]
I actually just tested out a patch for the User.upgrade method and it works for adding a webhook to a user provided you're upgrading to 'connect' permissions.
So the method now looks like so:
```
def upgrade(api_level=nil, webhook=nil)
        if api_level.nil?
          api_level = 'auth' unless self.permit? 'auth'
          api_level = 'connect' unless self.permit? 'connect'
        end
        opts = { access_token: self.access_token, upgrade_to: api_level }
        opts[:options] = {webhook: webhook}.to_json if !webhook.blank? && api_level == 'connect'

        res = Connection.post('upgrade', opts)

        # Reset accounts and transaction
        self.accounts = []
        self.transactions = []
        update(res)
      end
```
And you use it the same as before, restore a user (or create one)
`plaid_user = Plaid.set_user('test_chase', ['auth'])`
then just call it like so: `plaid_user.upgrade('connect','http://requestb.in/'`
the `.upgrade` method still works the same if you upgrade to something else and don't pass in a webhook url

**Comment by be9** [comment]
Closing as outdated.
