### ISSUE TITLE
List all items

### ISSUE THREAD

**Issue by Salimchorfi** [plaid/plaid-ruby#271]
Is there a function to list all items? I'm working in a development environment and haven't stored information about items.

I would like to delete them, but does not have the access_token.

**Comment by cgfarmer4** [comment]
Hi @Salimchorfi- we do not provide a way to list all items. If you launch in production, we recommend keeping track of these tokens to delete them.

Reminder that deleting items in development, will not give you access to more development items.

**Comment by cgfarmer4** [comment]
Please reach out to support if you have further concerns. https://dashboard.plaid.com/support/new/product-and-development/account-administration/request-tokens
