### ISSUE TITLE
Remove type from calls as required parameter 

### ISSUE THREAD

**Issue by j4ustin** [plaid/plaid-ruby#31]
"Type" is no longer a required parameter with every sandbox request - instead, access tokens are now in the format "test_{type}" (https://plaid.com/docs/#sandbox).  The previous style - of providing type={type} and access_token=test - still works, but is less user friendly.

**Comment by michaelckelly** [comment]
:+1: thanks @j4ustin!  Looking forward to this change!

**Comment by j4ustin** [comment]
This has been removed as of V1.4.0. Still reverse compatible for calls and tested.
