### ISSUE TITLE
Add user method to reconstruct user from auth_token for use in Plaid Gem

### ISSUE THREAD

**Issue by j4ustin** [plaid/plaid-ruby#33]
There is no way to recall a a user if the session has been ended (at least no easy way now). 

The user class needs a method to reconstruct a user based on a single auth_token being passed in as a parameter. This should also be noted in the wiki documentation.

**Comment by fredkelly** [comment]
There's probably a nicer approach here, as this doesn't actually perform the request, but it's doing the job for now.

**Comment by j4ustin** [comment]
@fredkelly I've added a method to the 1.4.1 gem based on something similar to what you built, but with a bit more user building on the backend. 

Now you can call ***Plaid.set_user(token,api_level=[])***, with the appropriate token and an array with the permissions the user has granted. This will rebuild the user.
