### ISSUE TITLE
Faraday::SSLError SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello

### ISSUE THREAD

**Issue by moustafasallam** [plaid/plaid-ruby#347]
Sometimes we receive the following error when try to connect to plaid endpoint. 

```
Faraday::SSLError
SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
```
The issue is that this is not always the case it could happen at certain times. Not sure what is the causes.

**Comment by Abdullah-F** [comment]
@phoenixy1 trying to upgrade from version 11, but I can not see any helpful notes [here](https://github.com/plaid/plaid-ruby/tags) that tells me what changed in newer versions. do you have a change log somewhere ?

**Comment by phoenixy1** [comment]
@Abdullah-F the interface to all endpoints has changed as we are now auto-generating the libraries. You can see some examples here https://github.com/plaid/plaid-ruby and more extensive examples with old and new library examples side by side in the API reference docs here: https://plaid.com/docs/api/

**Comment by phoenixy1** [comment]
Closing this issue right now as we don't have evidence it's relevant for version 14; please create a new issue if it is.
