### ISSUE TITLE
where's the routing number?

### ISSUE THREAD

**Issue by geermc4** [plaid/plaid-ruby#355]
According to [this](https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/api/plaid_api.rb#L803)

```
request = Plaid::AuthGetRequest.new(access_token: @access_token, options: { account_ids: [@account_id]})
response = @plaid_client.auth_get(request)
```

that should return the "bank account and bank identification numbers" but this is the response which doesn't have it

```
=> #<Plaid::AuthGetResponse:0x0000564d86c88140
 @accounts=
  [#<Plaid::AccountBase:0x0000564d86c839d8
    @account_id="BQRyGQ81WgTgAW8wkq1eHwloDkW73Js7k6V3K",
    @balances=#<Plaid::AccountBalance:0x0000564d86c83550 @available=100.0, @current=110.0, @iso_currency_code=nil, @last_updated_datetime=nil, @limit=nil, @unofficial_currency_code=nil>,
    @mask="0000",
    @name="Plaid Checking",
    @official_name="Plaid Gold Standard 0% Interest Checking",
    @subtype="checking",
    @type="depository">],
 @item=
  #<Plaid::Item:0x0000564d86c81cc8
   @available_products=["assets", "balance", "identity", "liabilities", "transactions"],
   @billed_products=["auth"],
   @consent_expiration_time=nil,
   @error=nil,
   @institution_id="ins_127989",
   @item_id="nK5xlKPg93IpWPJAN6QmCBw3zEqkepCArogle",
   @update_type="background",
   @webhook="">,
 @numbers=nil,
 @request_id="6YZBicZD9VWTgbB">
```

Also tried with `accounts_get` and the response looks the same

```
request = Plaid::AccountsGetRequest.new(access_token: @access_token, options: { account_ids: [@account_id]})
response = @plaid_client.accounts_get(request)




=> #<Plaid::AccountsGetResponse:0x00007f543872a5b8
 @accounts=
  [#<Plaid::AccountBase:0x00007f543872a2c0
    @account_id="BQRyGQ81WgTgAW8wkq1eHwloDkW73Js7k6V3K",
    @balances=#<Plaid::AccountBalance:0x00007f543872a018 @available=100.0, @current=110.0, @iso_currency_code=nil, @last_updated_datetime=nil, @limit=nil, @unofficial_currency_code=nil>,
    @mask="0000",
    @name="Plaid Checking",
    @official_name="Plaid Gold Standard 0% Interest Checking",
    @subtype="checking",
    @type="depository">],
 @item=
  #<Plaid::Item:0x00007f5438728fb0
   @available_products=["assets", "balance", "identity", "liabilities", "transactions"],
   @billed_products=["auth"],
   @consent_expiration_time=nil,
   @error=nil,
   @institution_id="ins_127989",
   @item_id="nK5xlKPg93IpWPJAN6QmCBw3zEqkepCArogle",
   @update_type="background",
   @webhook="">,
 @request_id="dujVrJWLct26WQy">
```

**Comment by geermc4** [comment]
Hey @stephenjayakar , the one on my post above is `6YZBicZD9VWTgbB`, just tried it again with `ryfhEnva7sVJksZ` and still have no numbers. I did upgrade to the recent 14.1 too and I have no `numbers`

**Comment by stephenjayakar** [comment]
hiya @geermc4! 

so I checked out your request id and noticed that the `apiVersion` for your request is `2017-03-08`. `plaid-ruby` only supports the latest api version. did you overwrite the `Plaid-Version` header that's default set in the generated client? that would explain why the object is empty as deserialization is probably failing. 

still unable to repro, but the api version i'm using (and is default set for ruby) is `2020-09-14`

**Comment by geermc4** [comment]
Can't find any mention of the code touching the version, also the client looks like it has the correct version

```
[10] pry(#<PlaidManager::DetailProvider>)> @plaid_client.api_client.default_headers
=> {"Content-Type"=>"application/json", "User-Agent"=>"Plaid Ruby v14.1.0", "Plaid-Version"=>"2020-09-14"}
```

**Comment by geermc4** [comment]
maybe something [here](https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/configuration.rb#L201)? added a `pry` in there

```
[1] pry(#<Plaid::Configuration>)> param_name
=> "Plaid-Version"
[2] pry(#<Plaid::Configuration>)> @api_key_prefix[param_name]
=> nil
[3] pry(#<Plaid::Configuration>)> @api_key[param_name]
=> nil
```

**Comment by geermc4** [comment]
Yes that's it @stephenjayakar , I had to explicitly tell it which version to use with `config.api_key["Plaid-Version"] = "2020-09-14"`, and now I get the numbers. Looks like that default isn't being used ?

**Comment by stephenjayakar** [comment]
thanks for the follow up! i'll investigate why the default isn't working, but glad I could help you fix your issue :)

**Comment by cgfarmer4** [comment]
@geermc4 I added this to the defaults in `14.2.0`. Hopefully that resolves having to manually do this going forward.
