### ISSUE TITLE
"automatically_verified" is not a valid verification_status

### ISSUE THREAD

**Issue by kirstiecook** [plaid/plaid-ruby#357]
Creating a stripe bank account token for Automated Microdeposit accounts is currently failing because automatically_verified is not currently contained in the list of allowed verification statuses.

ArgumentError: invalid value for "verification_status", must be one of ["pending_automatic_verification", "pending_manual_verification", "manually_verified", "verification_expired", "verification_failed"]. from plaid-14.0.0/lib/plaid/models/account_base.rb:192:in `verification_status='

Following docs on /sandbox/item/set_verification_status, the possible values from sandbox are "automatically_verified" and "verification_expired", but "automatically_verified" doesn't currently work. Haven't had a chance to see how this works outside of sandbox environment yet, but I imagine the problem would be the same..

Opened PR to demonstrate issue in https://github.com/plaid/plaid-ruby/pull/356

**Comment by phoenixy1** [comment]
14.1.0 has been released, this should now be resolved, let us know if it is not!
