### ISSUE TITLE
Inaccurate docs in Response Objects section

### ISSUE THREAD

**Issue by javierjulio** [plaid/plaid-ruby#371]
In the [Response Objects section](https://github.com/plaid/plaid-ruby#response-objects) states that response attributes can be accessed by both dot notation and brackets but that's inaccurate as of v14. It appears only dot notation is supported. I encountered this while upgrading from v11 to v14 as we were previously using brackets to retrieve values.

**Comment by phoenixy1** [comment]
thank you for pointing this out. Resolved with https://github.com/plaid/plaid-ruby/pull/382
