### ISSUE TITLE
Master branch?

### ISSUE THREAD

**Issue by hosh** [plaid/plaid-ruby#38]
Although I see references to gem `1.4.2` or `1.4.3` and mentions of fixes, I don't see them here.

I'd like the project to follow standard open-source processes to make it easier to follow code updates and make pull requests:

  1. `master` branch should contain the latest code
  2. The existing "stable" branches can continue
  3. tagged releases
  4. Follow semantic versioning http://semver.org/ ... tl;dr a project using semver (incrementing the minor number only when there are backwards-compatible changes) means you would only need a v1_0 stable and v2_0 stable branch

Following semantic versioning standards would mean let us make major, but breaking improvements to the gem. For example, #37 fixes a bug with passing connection options, but requires a breaking the method signature in order to fix it. There may be other architectural concerns that need to be addressed to make this gem more robust.

What do you guys think?

**Comment by j4ustin** [comment]
@hosh I agree completely with this change. I'll make the master the center, and keep the stable branches up. We can tag releases from here on out.
