### ISSUE TITLE
Missing Status fields in ItemGetResponse from missing version number in user agent

### ISSUE THREAD

**Issue by michaelkitson** [plaid/plaid-ruby#389]
Hey team, I was confused why ItemGetResponse would always have a null status field in our requests, and was surprised to see the value present in the item debugger and when manually performing the api call with curl.

I worked through any possible differences between the http requests made by curl vs this library and eventually narrowed it down to the user agent header.

When reproducing the same request with curl, providing the buggy user agent reproduced the error that we see using this library. Fixing the version string in the library resolved the issue (`"Plaid Ruby v#"` -> `"Plaid Ruby v#{VERSION}"`).

The offending line:
https://github.com/plaid/plaid-ruby/blob/eeaea4585f0d746f42de2ea1d023b26751888d4f/lib/plaid/api_client.rb#L33

The bug was introduced in https://github.com/plaid/plaid-ruby/commit/442a6391a79635eac969dee92c56ceb2137a281f

Happy to provide ruby or curl examples if necessary, let me know.

Thanks!

**Comment by phoenixy1** [comment]
Thanks for the extremely detailed bug report. This looks like a typo in some interpolation. Should have a fix soon after Thanksgiving, I think.

**Comment by phoenixy1** [comment]
This should be fixed with today's release. Feel free to reopen/create a new issue if it's not resolved.
