### ISSUE TITLE
Documentation / example of implementing the MFA process?

### ISSUE THREAD

**Issue by robbfitzsimmons** [plaid/plaid-ruby#39]
Thanks for the gem and am loving the changes in 1.4 (better set_user methods made retrieving information dramatically easier halfway through my work).

I'm having trouble with the MFA process as documented. Returning 402 Request Failed errors when trying to set_user with the access token in between steps of the MFA process. However, am getting the pending_mfa_response.

Could you link to an implementation of the whole process, and include in the wiki?

**Comment by j4ustin** [comment]
@robbfitzsimmons Yes! The gem is going through a bit of refactoring as we move towards open sourced standards. I'll update this ASAP.

**Comment by robbfitzsimmons** [comment]
@j4ustin Great! Any idea whether that refactoring lands this week, or afterwards?

Trying to push a product end of this week, and attempting to figure out what I can do within that timeframe.

**Comment by j4ustin** [comment]
@robbfitzsimmons It'll be pushed out slowly over the next few weeks. @hosh will be providing some PR's over that time. I'll take a look through set user, and MFA tonight so you can at least get that version out.

**Comment by robbfitzsimmons** [comment]
Thanks!

**Comment by hosh** [comment]
@robbfitzsimmons in the meantime, if you know how to read this spec, here is an example: https://github.com/plaid/plaid-ruby/blob/master/spec/user_spec.rb#L98-L103

So:

```ruby
user = Plaid.add_user('auth','plaid_test','plaid_good','chase',nil, {list: true})
user.select_mfa_method({mask:'xxx-xxx-5309'})
user.mfa_authentication(1234)
```

(The above has `list: true` so it creates a third step where you show the user various options for getting the authentication code).

**Comment by hosh** [comment]
@robbfitzsimmons huh, though the `402 Request Failed` sounds interesting. I haven't seen anything in the specs where we're trying to use `set_user` to rehydrate something that has MFA. Do you have some sample code with what you are trying to do? We can probably adapt it into the testing suite -- make sure it is not a bug on the gem's end of things.

**Comment by robbfitzsimmons** [comment]
Thanks guys; it's entirely possible I'm doing something dumb but I've been through the docs a bunch of times trying to understand what's going on with MFA. Just gonna post the relevant stuff below.

I've got the whole repo [here](https://github.com/fieldthree/leverage-rails); it's a Rails app.

Specifically I'm struggling to set the instance variable in the MFA flow. I'm redirecting and have stored the user's auth_token after calling `get_user`. I'm trying to instantiate that user in my controller:

```
def mfa
    @inst_account = InstitutionAccount.find(params["inst_acc"])
    @access_token = @inst_account.access_token

    @mfas         = Plaid.set_user(@access_token, api_level=['connect']).pending_mfa_questions["mfa"]
  end
```
and then attempting to call it here in my account `create`:

```
  # POST /institution_accounts
  # POST /institution_accounts.json
  def create
    if params.has_key?("mfa") == false
      user = Plaid.add_user("connect", params["username"], params["password"], params["type"], {list: true})
      
      inst_account = current_user.institution_accounts.new
      inst_account.access_token = user.access_token
      inst_account.save

      mfas = user.pending_mfa_questions

      # Here we're testing for Plaid's api_response indicating MFA is needed.
      if not user.api_res == "Requires further authentication"
        redirect_to root_path, notice: "Yay, your access token was #{inst_account.access_token}"
      else
        redirect_to mfa_path("inst_acc" => inst_account.id), notice: "Need MFA, length was #{mfas.length.to_s}"
      end

    elsif params.has_key?("mfasub") == false
      mfatype = params["mfatype"]
      access_token = params["at"]
      
      # LOOKS LIKE WE CAN'T USE SET_USER BEFORE MFA AUTH FINISHES?

      user =  Plaid.set_user(access_token, api_level=['connect'])
      user.select_mfa_method({mask: mfatype})

      redirect_to mfasub_path("at" => access_token), notice: "Need MFA submission, mfa type was #{mfatype}"

    else
      conf = params["confirmation"]
      access_token = params["at"]
      user =  Plaid.set_user(access_token, api_level=['connect'])
      user.mfa_authentication(conf)

      redirect_to root_path, notice: "You're done!"

    end
  end
```
How would you recommend doing this setup?

Thanks!

**Comment by j4ustin** [comment]
@robbfitzsimmons 

I have a few points about the setup.

```#set_user``` should only be used on a fully authenticated user who has received a valid auth token from Plaid. This method not only sets the access token to the Plaid::User, but also tries to access the permission levels that the user has already authenticated.

This method was built to help users of the gem reconstruct already authenticated users and reconnect to their accounts once they had access. If the access was revoked, then the user would have to flow through the ```#add_user``` flow again. ***In the future we may switch ```set_user``` out for something more flexible, but for now thats it's only purpose.***

Adding a user who requires MFA should flow through ```#add_user``` first, then through ```User#mfa_authentication``` once you receive a response from Plaid. You should then check ```api_res``` to see if the user has to flow through more authentication.

In my opinion you should separate your Plaid authentication from your User creation. This should then get even more granular into types of authentication required (none, code, selection, etc.). Plaid provides an institution endpoint (ref: https://plaid.com/docs/#institutions, gem-ref: https://github.com/plaid/plaid-ruby/wiki/Plaid::Institution) so you can tell which institutions require MFA and what type of MFA they will return. 

This will keep your code well organized so you can test it thoroughly, and fix any issues that arise for specific types of MFA or add in any new MFA types as they are developed in the future.  

Let me know if this makes sense. Also, if anyone else has opinions on this please chime in below!

**Comment by robbfitzsimmons** [comment]
Thanks -- this was very helpful and I've made a bunch of progress.  I now have it such that the user can pick from the available "pending mfa questions" after add_user'ing.

However, I'm now confused about how to call select_mfa_method over in a different controller/action without being able to somehow recover the Plaid::User object from the original add_user call.  I tried storing the Plaid::User object in a session variable, but that serializes it into a hash, thus rendering us unable to invoke any methods off of it.  If not with set_user, how do I get that Plaid::User back?

(Alternatively, can you point me to someone who has done this whole flow -- prompting to connect to an institution, then proceeding through various necessary levels of mfa-auth as needed -- in a Rails app?  I feel like I'm writing a LOT of code to get this working out-of-the-box.)

**Comment by j4ustin** [comment]
@robbfitzsimmons 

I don't have an example app where someone has implemented the gem. Depending on the apps goals this implementation can range from very simple to very complex. 

If I were building this out in Rails I would persist the user across one session after the initial instantiation using a class variable in my controller. That should fix the issue your running into as long as the session persists.

**Comment by robbfitzsimmons** [comment]
Thanks; using a class variable worked. That leaves me unable to use multithreaded servers, but that's OK for now I guess.

Now I'm just struggling with one last (I think) thing: how do we construct what's being passed to select_mfa_method based on the pending_mfa_question they would have picked?

For example, 
```
mfapicked = params["mfapicked"] #"What is your favorite color?"
      puts "mfapicked was #{mfapicked}"
      # so, which entry in pending_mfas do we send back?
      pickedHash = {}
      @@user.pending_mfa_questions["mfa"].each do |pending|
        puts "pending was #{pending}" #e.g. {"question" => "What is your fav color", "questionId" => "q1"}
        if pending.values[0].to_s == mfapicked.to_s

         #SEE HERE attempt to construct hash to pass into select_mfa_method
          pickedHash = { pending.keys[0] => pending.values[0] } 
          #e.g. { "question" => "What is your fav color" }
        end
      end
      puts "pickedHash was #{pickedHash}"
      @@user.select_mfa_method(pickedHash)
```

The last line triggers a Request Failed (no further msg) from Plaid, which leads me to think that what I'm passing in -- e.g. { "question" => "What is your fav color" } -- is not of the format Plaid is expecting (e.g. {mask:'xxx-xxx-5309'}).  I feel like I'm close here!

**Comment by j4ustin** [comment]
@robbfitzsimmons 

A class instance variable should be fine also as long as the session persists. (@user vs. @@user)

You don't need to select_mfa_method unless the bank allows you to. This would be used to specify whether the user will get a code, question, or some other type of MFA that the bank allows. You can find out which institutions allow that here: https://plaid.com/docs/#institutions

Once you have a pending_mfa_question all you need to do is pass the users MFA answer back using ```User#mfa_authentication(answer)```. 

I think the formatting of the wiki is tripping you up a bit, sorry about that. Be sure to read the Plaid documentation in full, it'll help you get a grasp of what we do with the library.

**Comment by robbfitzsimmons** [comment]
Thanks, Justin. General Plaid docs are handy, and have been referencing to put the Ruby objects in context.

I think what you're suggesting here is that I write a separate MFA flow for each bank, or at least separate flows for question and code types of MFA? I had been looking to avoid a big block for that but if that's the way the library needs it, OK.

Will keep chugging on that and report back; happy to help document when I've got it running but I really think building out each MFA flow in the wiki would be enormously helpful for people like me trying to pick this up and be productive quickly.

**Comment by robbfitzsimmons** [comment]
@j4ustin I'd also like to apologize for overloading this thread - I thought you were a Plaid employee. I'll keep chugging and really appreciate both of your willingness to help!

**Comment by j4ustin** [comment]
@robbfitzsimmons 

No worries! Plaid is a great tool, so I'm happy to help out. 

I think you should have a small amount of code for each type of authentication you encounter. Likely they will end up returning code with the same end result (eg ```#mfa_authentication```) You can set flagsfor your institutions so you can route the request to the correct handler.  

This will make your code easy to maintain and testable.

**Comment by hosh** [comment]
I have not implemented MFA on my app yet, so I have only a superficial understanding of the issue.

The problem I see is that a Rails app is inherently stateless, but the way the Plaid gem is designed for MFA is that you have to carry the original user object around. I don't think class methods are the way to go. The reason for that is if you have multiple requests coming in and you have something like multithreaded turned on. 

I'm thinking there is a better way to do that:

  1. The non-breaking way is to add a top-level Plaid.select_mfa and Plaid.snd_mfa code, where it takes an access token as the first argument. (I could be wrong about this -- I usually get a much better understanding of the issues once I jump in and start coding).

  2. Change the Plaid gem architecture. One of the thing that frustrates me about the current gem is that that the level of abstraction is awkward. My app is designed to use webhooks, so it won't be attempting to query Plaid in real time. Between that, and the issue with the MFA when calling from a stateless architecture like Rails, I think we really need to separate the authentication process from the data retrieval process. How that might look like, I'm not entirely sure right now.

I'll be getting to MFA in my app sometime next week, and will probably open a PR that implements (1). 

@robbfitzsimmons as far as multiple MFA flows per institution, that is pretty much what I have sketched out in my mind for my app. I'm writing an internal DSL that will describe the MFA requirements, such that as Plaid adds more institutions or drops MFA requirements from existing ones, these can be changed to match. If the level of abstraction is right though, maybe I can extract that out and put it somewhere, maybe even in the Plaid gem itself.

**Comment by robbfitzsimmons** [comment]
Folks, I've worked with a friend to implement the full MFA flow this weekend and will attempt to abstract some boilerplate code for future users to pick up.

Thanks again for all your help; closing this.

**Comment by SupremeA** [comment]
@robbfitzsimmons That boilerplate code would be much appreciated!

**Comment by robbfitzsimmons** [comment]
@SupremeA I'm implementing it here:
https://github.com/fieldthree/leverage/tree/plaid-ruby-auth

FYI the approach on the master branch will change in the next few days as I move to a JavaScript-driven implementation, but will maintain the old approach on this separate branch for reference.

**Comment by arcreative** [comment]
I'd hate to be THAT guy, but I ended up just writing a simple wrapper class for those who don't/can't persist the user object across sessions:  https://gist.github.com/arcreative/4982b180d641d3174c2c

This lets you:

1. Obtain an access token with the connect method
2. Submit additional MFA responses via the `submit_mfa` method
3. `get` accounts and transactions with a working access_token

Hope this helps!
