### ISSUE TITLE
Need A Better Check for `Rails.logger`

### ISSUE THREAD

**Issue by benhutton** [plaid/plaid-ruby#406]
This is not a safe way to check if an app is a rails app: https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/configuration.rb#L161

We are NOT a rails app, yet `Rails` is defined because we use one of Rails' spun-off gems: https://github.com/rails/rails-html-sanitizer/blob/master/lib/rails-html-sanitizer.rb#L6

We are not actually loading the rails gem that would define `Rails.logger`. In our system, `Rails` is just a module.

Ideally, the aforementioned line would get replaced as follows:

```
@logger = (defined?(Rails) && Rails.respond_to?(:logger)) ? Rails.logger : Logger.new(STDOUT)
```

**Comment by cgfarmer4** [comment]
Hey @benhutton - we're working on a fix here and will update with the next minor version. Thanks for calling this out!

**Comment by vorpus** [comment]
Hi @benhutton - Could you see if version 14.12.1 solves your rails checking problem? Thanks!

**Comment by benhutton** [comment]
@vorpus yes it does. Thank you!
