### ISSUE TITLE
client_id must be a properly formatted, non-empty string

### ISSUE THREAD

**Issue by Paulsonbigi** [plaid/plaid-ruby#418]
I am pass my unique client_id and i keep getting `client_id must be a properly formatted, non-empty string`
`false,
        {
            "display_message": null,
            "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
            "error_code": "INVALID_FIELD",
            "error_message": "client_id must be a properly formatted, non-empty string",
            "error_type": "INVALID_REQUEST",
            "request_id": "2Zkd4lBqNNZx7vT",
            "suggested_action": null
        },`

 What am i doing wrong

**Comment by phoenixy1** [comment]
Most likely there's a data entry error with your `client_id` -- if you can't figure it out on your end, you can use the Dashboard to file a developer support ticket with the information above, and Support can use the request_id to look up how your request was received by the Plaid servers to help troubleshoot the problem with how the `client_id` was passed.
