### ISSUE TITLE
Configuring a timeout works correctly, but raises a `Plaid::ApiError` instead of some kind of timeout error

### ISSUE THREAD

**Issue by ctlevi** [plaid/plaid-ruby#428]
Version 13 and before allowed us to set a timeout for the client, and a `Faraday::TimeoutError` was raised. But in the latest version, 15.6.0, a `Plaid::ApiError` is raised and all the fields are null. So I can't really tell if it is a timeout error, or a Plaid error.

I would expect the timeout error that is raised to continue to be a `Faraday::TimeoutError`. Or at least for the `Plaid::ApiError` to say that it is a client imposed timeout error.

How to reproduce:
* Configure the client with a 1 second timeout: `api_client.connection.options[:timeout] = 1`
* Call an API that takes longer than 1 second. I used the institutions API with a large count
* A `Plaid::ApiError` with all nil fields is raised

**Comment by phoenixy1** [comment]
cc: @vorpus

**Comment by ghernandez-plaid** [comment]
Hi @Maimer ! I hope all is well. My name is Gilberto and I’m on the Developer Relations team at Plaid. Our team is interested in expanding our Plaid community and we’re conducting a bit of research to learn more about how devs engage with us.

I was wondering if you'd be interested in participating in a 30 minute research session with me and a member of our research team? You would be compensated with a gift card for your time. If you’re interested, let me know and I can send over the Calendly invite so we can schedule some time (we could switch to email, Twitter DM, etc., for communication). Thanks! (Also, @ctlevi – the invite is also open to you as well in case you're interested 🙂 )

**Comment by phoenixy1** [comment]
@vorpus just wanted to raise this again -- should we file an issue on the internal jira?

**Comment by phoenixy1** [comment]
@otherchen Any ideas on this one? Do you think we should file an issue on the internal Jira?

**Comment by otherchen** [comment]
Yeah, I think what @Maimer suggested - introducing a new timeout error type - seems like the right path forward! I'll create a JIRA to track this internally.

**Comment by kyledcline** [comment]
Is this issue resolved in later versions of the gem?

**Comment by phoenixy1** [comment]
@kyledcline unfortunately I don't believe it's been resolved.

**Comment by Maimer** [comment]
@kyledcline @phoenixy1 It hasn't been fixed in regards to introducing a new timeout error, but at least the string error message is preserved as of version 24.3 in this PR: https://github.com/plaid/plaid-ruby/pull/482, specifically this line: https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/api_error.rb#L35. So if you were using the patch I was using earlier you no longer need it if you are using version 24.3 or newer:

```ruby
[1] pry(main)> require 'plaid'
=> true
[2] pry(main)> error = Plaid::ApiError.new('Connection timed out')
=> #<Plaid::ApiError: Connection timed out>
[3] pry(main)> error.message
=> "Connection timed out"
[5] pry(main)> Plaid::VERSION
=> "24.3.0"
[6] pry(main)>
```

**Comment by phoenixy1** [comment]
This is now resolved in the latest ruby client library. See https://github.com/plaid/plaid-ruby/pull/483
