### ISSUE TITLE
Plaid return false on require 'plaid' and some classes didn't work

### ISSUE THREAD

**Issue by hellojunaydiqbal** [plaid/plaid-ruby#433]
Hello Team,
I'm facing some issues regarding `require 'plaid'` when I installed gem with version 15.9.0 to downward till 10.0.0. So all the gems facing the same issue.
And another thing is that when I call Plaid::Configuration -> `configuration = Plaid::Configuration.new` it showed me an error of `uninitialized constant Plaid::Configuration (NameError)` and same issue with `api_client = Plaid::ApiClient.new` and `Plaid::LinkTokenCreateRequest.new`. 

So what should I do?

**Comment by hellojunaydiqbal** [comment]
Kindly reply to this comment to resolve issue @hosh @otherchen @pbernasconi

**Comment by StepanenkoArtem** [comment]
Faced this issue too. And as I see nobody worries about it? 
@hellojunaydiqbal did you find a solution?

**Comment by StepanenkoArtem** [comment]
For those who faced this issue..

**Comment by FutoRicky** [comment]
My issue was that I had the latest plaid version and my project is still on ruby 2.7.6. The latest Plaid version requires Ruby 3+, fixed my issue by specifying the version of gem ` gem 'plaid', '~> 13.2'` Temporary fix while I get some time to upgrade my ruby version.
