### ISSUE TITLE
Support Faraday 2

### ISSUE THREAD

**Issue by dbil25** [plaid/plaid-ruby#435]
Faraday 2 has been out for a while, but this gems asks for Faraday 1.

Is it possible to bump the dependencies so that it can support faraday 2? Thank you very much!

**Comment by phoenixy1** [comment]
cc: @otherchen I have filed a ticket in our internal Jira to track this and cc:ed you on it.

**Comment by rafaelpetry** [comment]
Any updates on this? We can't update some of our dependencies that now require Faraday 2 because the Plaid gem is pinned to 1.x.

**Comment by phoenixy1** [comment]
@rafaelpetry Yes, as a matter of fact! Thanks to @walski we are literally in the process of fixing it now (as in, the PR is going through CI) and the fix will be available in the next client library release, which should be within the next week or so.
