### ISSUE TITLE
Confusion with calling items in transaction response

### ISSUE THREAD

**Issue by SupremeA** [plaid/plaid-ruby#44]
Hello I am working with the gem but I am having issue with how to pull specific items from the array that comes back for transactions on a User. I am missing something with the gem documentation. Using the test user and account how would I pull the amount for "Payroll" using the category id. I know this is probably a basic question but I am struggling to see how to do it. Any help would be greatly appreciated.

P.S. I can see the transaction in the array when I call User.transactions in the ruby console but cant seem to pull specific items

**Comment by j4ustin** [comment]
@SupremeA 

The transactions are returned as an array of objects. In order to pull the specific "Payroll" transactions you can use the Ruby Enumerable module. 

Based on the small description you put up it seems like ```#partition``` is what your looking for. (Documentation: http://ruby-doc.org/core-2.2.1/Enumerable.html#method-i-partition). 

I haven't done any official testing but it seems like something like this should work: 

```ruby 
payroll_transactions, other_transactions = user.transactions.partition { |transaction| transaction.name == "Payroll" }
```

Again, not sure if that is the right syntax, but its seems like the right direction. Hope that helps out.

**Comment by hosh** [comment]
@SupremeA if you are trying to filter out transactions whose category falls under "payroll", you can use `#select`:

```
payroll_transactions = user.transactions.select { |t| t.category_id == 10203 }
```

I am making up the number `10203` -- substitute it for the correct `category_id`

**Comment by SupremeA** [comment]
Thanks for your help @hosh, I tried the select method and I got this error.

    2.1.3 :103 > payroll_transactions = User.transactions.select { |t| t.category == 21009000 }
    NoMethodError: undefined method `category' for #<Array:0xc18e26c>

Also tried the partition method you mentioned @j4ustin. Got the same error...

    2.1.3 :105 > payroll_transactions, other_transactions = User.transactions.partition { |transaction| transaction.category == "21009000" }
    NoMethodError: undefined method `category' for #<Array:0xc18e26c>

**Comment by j4ustin** [comment]
@SupremeA What does your transactions array look like? Can you see a single transaction with ```category``` attached?

**Comment by SupremeA** [comment]
2.1.3 :029 > user
      => #<Plaid::User:0xbcda9b4 @transactions=[["0AZ0De04KqsreDgVwM1RSRYjyd8yXxSDQ8Zxn", "XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo", 200, "ATM Withdrawal", {"location"=>{"city"=>"San Francisco", "state"=>"CA"}}, nil, false, {"location"=>{"city"=>1, "state"=>1}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Withdrawal", "ATM"], "21012002"], ["3mg4qV4JZycjewvKEzrLTYMzdr1MmvcO4Z3zX", "XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo", 240, "Online Transfer from External Sav ...3092", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Account Transfer"], "21001000"], ["KdDjmojBERUKx3JkDdO5IaRJdZeZKNuK4bnKJ1", "pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k", 2307.15, "Apple Store", {"location"=>{"address"=>"1 Stockton St", "city"=>"San Francisco", "state"=>"CA"}}, nil, false, {"location"=>{"address"=>1, "city"=>1, "state"=>1}, "name"=>0.2}, {"primary"=>"place"}, ["Shops", "Computers and Electronics"], "19013000"], ["DAE3Yo3wXgskjXV1JqBDIrDBVvjMLDCQ4rMQdR", "nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy", 3.19, "Gregorys Coffee", {"location"=>{"address"=>"874 Avenue of the Americas", "city"=>"New York", "state"=>"NY"}}, nil, false, {"location"=>{"address"=>1, "city"=>1, "state"=>1}, "name"=>0.2}, {"primary"=>"place"}, ["Food and Drink", "Restaurants", "Coffee Shop"], "13005043"], ["1vAj1Eja5BIn4R7V6Mp1hBPQgkryZRHryZ0rDY", "nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy", 80, "ATM Withdrawal", {"location"=>{"city"=>"San Francisco", "state"=>"CA"}}, nil, false, {"location"=>{"city"=>1, "state"=>1}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Withdrawal", "ATM"], "21012002"], ["zq7MLAM4N3cjeKvXP9YqtBJXvZeajJCkjQakYv", "QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK", -240, "Online Transfer from Chk ...1702", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Account Transfer"], "21001000"], ["96d5AO5gLjC9EowVyn5OCBRjJR9LaOHJnBVJzd", "nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy", 240, "Online Transfer to Sav ...9606", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Account Transfer"], "21001000"], ["VK0EQ5Ea13u9Qwzm6nA8CNaze8gdJoCJvx6JDO", "nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy", -0.93, "Interest Payment", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>0.2}, {"primary"=>"unresolved"}, ["Interest"], "15000000"], ["aJPEm5EVqxF6yk8K5nPeFbDpnPR57wI3xMR3pP", "pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k", 12.74, "Golden Crepes", {"location"=>{"address"=>"262 W 15th St", "city"=>"New York", "coordinates"=>{"lat"=>40.740352, "lon"=>-74.001761}, "state"=>"NY"}}, nil, false, {"location"=>{"address"=>1, "city"=>1, "state"=>1}, "name"=>0.2}, {"primary"=>"place"}, nil, nil], ["moPE4dE1yMHJX5pmRzwrcvpQqPdDnZHEKPREYL", "nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy", 7.23, "Krankies Coffee", {"location"=>{"address"=>"211 E 3rd St", "city"=>"Winston Salem", "state"=>"NC"}}, nil, false, {"location"=>{"address"=>1, "city"=>1, "state"=>1}, "name"=>0.2}, {"primary"=>"place"}, ["Food and Drink", "Restaurants", "Coffee Shop"], "13005043"], ["P1xJboJA5Ls31gJrMQEBU5dZD3NmPrH5R6g5jL", "pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k", 118.23, "Banana Republic", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>0.2}, {"primary"=>"digital"}, ["Shops", "Digital Purchase"], "19019000"], ["dRBp95pEwZfMXENvpw3YHY43VNK4LVSP7RkPpA", "nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy", -800, "Venmo Cashout 18375552", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Third Party", "Venmo"], "21010001"], ["moPE4dE1yMHJX5pmRzwrcvpkxdopLxtEKPREYo", "nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy", 120, "Venmo Payment 16991172", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Third Party", "Venmo"], "21010001"], ["JmN0JX0q5EcaQJM9ZbOwUYyyp607m4u3PR63Vn", "pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k", 5.32, "Octane Coffee Bar and Lounge", {"location"=>{"address"=>"1009 Marietta St Nw # B", "city"=>"Atlanta", "state"=>"GA"}}, nil, false, {"location"=>{"address"=>1, "city"=>1, "state"=>1}, "name"=>0.2}, {"primary"=>"place"}, ["Food and Drink", "Restaurants", "Coffee Shop"], "13005043"], ["4r0aBVa85Kt3BDPk10a4U5OD3XKjE7Hzxpez6B", "pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k", 28.57, "Papa Johns Pizza", {"location"=>{"address"=>"2625 David Dr", "city"=>"Metairie", "coordinates"=>{"lat"=>29.999986, "lon"=>-90.21869}, "state"=>"LA", "zip"=>"70003"}}, nil, false, {"location"=>{"address"=>1, "city"=>1, "state"=>1, "zip"=>1}, "name"=>0.2}, {"primary"=>"place"}, ["Food and Drink", "Restaurants", "Pizza"], "13005012"], ["eJXpMzpR65FP4RYno6yjhBDxgkM6pXC9RKM9o3", "QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK", -3042.44, "Company Payroll", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Payroll"], "21009000"]], @permissions=["connect"], @access_token="test_wells", @api_res="success", @info={}, @information=#<Plaid::Information:0xbcda824>, @accounts=[#<Plaid::Account:0xbcda61c @available_balance=1203.42, @current_balance=1274.93, @institution_type="fake_institution", @id="QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK", @type="depository", @name=[nil, 1203.42, 1274.93, "fake_institution", "QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK", "depository"], @meta={"number"=>"9606", "name"=>"Plaid Savings"}, @numbers="Upgrade user to access routing information for this account">, #<Plaid::Account:0xbcda34c @available_balance=1081.78, @current_balance=1253.32, @institution_type="fake_institution", @id="nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy", @type="depository", @name=[nil, 1081.78, 1253.32, "fake_institution", "nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy", "depository"], @meta={"number"=>"1702", "name"=>"Plaid Checking"}, @numbers="Upgrade user to access routing information for this account">, #<Plaid::Account:0xbcd9ed8 @available_balance=7205.23, @current_balance=7255.23, @institution_type="fake_institution", @id="XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo", @type="depository", @name=[nil, 7205.23, 7255.23, "fake_institution", "XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo", "depository"], @meta={"number"=>"5204", "name"=>"Plaid Premier Checking"}, @numbers="Upgrade user to access routing information for this account">, #<Plaid::Account:0xbcd9208 @available_balance=9930, @current_balance=2275.58, @institution_type="fake_institution", @id="pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k", @type="credit", @name=[nil, 9930, 2275.58, "fake_institution", "pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k", "credit"], @meta={"limit"=>12500, "number"=>"3002", "name"=>"Plaid Credit Card"}, @numbers="Upgrade user to access routing information for this account">], @pending_mfa_questions="", @account=#<Plaid::Account:0xbcd9208 @available_balance=9930, @current_balance=2275.58, @institution_type="fake_institution", @id="pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k", @type="credit", @name=[nil, 9930, 2275.58, "fake_institution", "pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k", "credit"], @meta={"limit"=>12500, "number"=>"3002", "name"=>"Plaid Credit Card"}, @numbers="Upgrade user to access routing information for this account">, @transaction=#<Plaid::Transaction:0xbcd467c @account="QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK", @amount=-3042.44, @name="Company Payroll", @meta={"location"=>{}}, @location=nil, @pending=false, @score={"location"=>{}, "name"=>1}, @type={"primary"=>"special"}, @category=["Transfer", "Payroll"], @category_id="21009000", @id=["eJXpMzpR65FP4RYno6yjhBDxgkM6pXC9RKM9o3", "QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK", -3042.44, "Company Payroll", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Payroll"], "21009000"]>, @type=nil>

**Comment by j4ustin** [comment]
It looks like only one of those transactions has a category attached, its tough to tell just by glancing. Can you confirm that?

**Comment by SupremeA** [comment]
I see the category number after each transaction but I don't see a key specific to the transaction showing that this is the category for example, at the end of the array I see this...

    @id=["eJXpMzpR65FP4RYno6yjhBDxgkM6pXC9RKM9o3", "QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK", -3042.44, "Company Payroll", {"location"=>{}}, nil, false, {"location"=>{}, "name"=>1}, {"primary"=>"special"}, ["Transfer", "Payroll"], "21009000"]>, @type=nil> 

So I see the category number (21009000) but I don't see a key identifying it and if I run:

    t.include?('21009000')

I get back: 

       => false

**Comment by SupremeA** [comment]
And yes, you are correct in this array I only see the 1 category and category_id. I will have to search by category_id or name in my app. However, I get the same error in either case.

**Comment by j4ustin** [comment]
@SupremeA So these transaction objects are returning without keys? Can you loop through these transactions, and see what type one object in the transactions array returns?

**Comment by SupremeA** [comment]
2.1.3 :007 > tenant.transactions.each { |x| puts x }

    0AZ0De04KqsreDgVwM1RSRYjyd8yXxSDQ8Zxn
    XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo
    200
    ATM Withdrawal
    {"location"=>{"city"=>"San Francisco", "state"=>"CA"}}

    false
    {"location"=>{"city"=>1, "state"=>1}, "name"=>1}
    {"primary"=>"special"}
    Transfer
    Withdrawal
    ATM
    21012002
    3mg4qV4JZycjewvKEzrLTYMzdr1MmvcO4Z3zX
    XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo
    240
    Online Transfer from External Sav ...3092
     {"location"=>{}}

    false
       {"location"=>{}, "name"=>1}
       {"primary"=>"special"}
        Transfer
        Account Transfer
        21001000
        KdDjmojBERUKx3JkDdO5IaRJdZeZKNuK4bnKJ1
        pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k
        2307.15
        Apple Store
        {"location"=>{"address"=>"1 Stockton St", "city"=>"San Francisco", "state"=>"CA"}}

    false
    {"location"=>{"address"=>1, "city"=>1, "state"=>1}, "name"=>0.2}
    {"primary"=>"place"}
    Shops
    Computers and Electronics
    19013000
    DAE3Yo3wXgskjXV1JqBDIrDBVvjMLDCQ4rMQdR
    nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy
    3.19
    Gregorys Coffee
    {"location"=>{"address"=>"874 Avenue of the Americas", "city"=>"New York", "state"=>"NY"}}

    false
    {"location"=>{"address"=>1, "city"=>1, "state"=>1}, "name"=>0.2}
    {"primary"=>"place"}
    Food and Drink
    Restaurants
    Coffee Shop
    13005043
    1vAj1Eja5BIn4R7V6Mp1hBPQgkryZRHryZ0rDY
    nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy
    80
    ATM Withdrawal
    {"location"=>{"city"=>"San Francisco", "state"=>"CA"}}

    false
    {"location"=>{"city"=>1, "state"=>1}, "name"=>1}
    {"primary"=>"special"}
    Transfer
    Withdrawal
    ATM
    21012002
        zq7MLAM4N3cjeKvXP9YqtBJXvZeajJCkjQakYv
        QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK
        -240
        Online Transfer from Chk ...1702
        {"location"=>{}}

**Comment by hosh** [comment]
@SupremeA 

What version of the gem are you using? The code that is in master returns an array of`Plaid::Transaction` objects, not an array of arrays.

**Comment by SupremeA** [comment]
plaid (1.4.3) according to gem check

**Comment by hosh** [comment]
@SupremeA that's really weird. Can you try switching it to the master branch in the Gemfile and seeing if you are getting the same errors?

**Comment by SupremeA** [comment]
Switching to the master branch? Not sure what you mean, do you mean submitting to github?

**Comment by hosh** [comment]
In your Gemfile:

```
gem 'plaid', git: 'git://github.com/plaid/plaid-ruby.git'
```

And then a `bundle update plaid`

**Comment by SupremeA** [comment]
DONE! That GOT IT!

Did a search

    user.transactions.select { |t| t.category_id == "21009000" }

Got back the specific item!

    => [#<Plaid::Transaction:0xc3546a0 @id="eJXpMzpR65FP4RYno6yjhBDxgkM6pXC9RKM9o3", @account="QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK", @amount=-3042.44, @name="Company Payroll", @meta={"location"=>{}}, @location=nil, @pending=false, @score={"location"=>{}, "name"=>1}, @type={"primary"=>"special"}, @category=["Transfer", "Payroll"], @category_id="21009000">] 

I think that it!

Thanks for your help!!!!!!!!!!!!!!

**Comment by hosh** [comment]
@SupremeA keep in mind, the master branch is the latest code, but not always going to be stable. I'm working with @j4ustin to get fixes and refactorings in. Once that's stable, you'll want to go back to the latest stable release, or at least, one of the stable branch releases.

You can also fix the gem to a specific commit like so:

```
gem 'plaid', git: 'git://github.com/plaid/plaid-ruby.git', ref: '030e822bc8d64c8a73b8058d6abfd9088951b5c9'
```

That pins it to that git ref, which is the current HEAD. But when we add new changes, a `bundle update` will not move it.

**Comment by SupremeA** [comment]
Ok, thanks! I will note that
