### ISSUE TITLE
Invalid Attributes

### ISSUE THREAD

**Issue by steven-searcy** [plaid/plaid-ruby#486]
I'm attempting to use the following attributes with /link/token/create: `required if supported products` and `optional products`, however I'm getting this error message:

`optional_products` is not a valid attribute in `Plaid::LinkTokenCreateRequest`

Are these not supported within the SDK? If I remove the optional_products attribute here, I'm not receiving any issues.

```
request = Plaid::LinkTokenCreateRequest.new({
      user: { client_user_id: user_id },
      client_name: client_name,
      products: %w[transactions],
      optional_products: %w[liabilities],
      country_codes: ["US"],
      language: "en",
      account_filters: { credit: { account_subtypes: ["credit card"] } } 
    })
```

**Comment by phoenixy1** [comment]
@steven-searcy can you confirm that you are using the latest version of the plaid-ruby client library? Optional products is definitely included in the latest version: https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/models/link_token_create_request.rb#L191

**Comment by jon-mcclung-fortyau** [comment]
> @steven-searcy can you confirm that you are using the latest version of the plaid-ruby client library? Optional products is definitely included in the latest version: https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/models/link_token_create_request.rb#L191

Thank you, this fixed it for us.
