### ISSUE TITLE
add support for exchange_token endpoint

### ISSUE THREAD

**Issue by fredkelly** [plaid/plaid-ruby#53]
As detailed [here](https://github.com/plaid/project-csa#exchange_token-endpoint).

**Comment by michaelckelly** [comment]
Thanks for opening this, @fredkelly.  Here's an updated link to the endpoint docs: https://github.com/plaid/link#exchange_token-endpoint.

**Comment by fredkelly** [comment]
aha, a little nicer than my effort :+1:
