### ISSUE TITLE
Add name of account holder to response

### ISSUE THREAD

**Issue by SupremeA** [plaid/plaid-ruby#67]
I am working on a project that looks at a users bank information and I noticed that for all the information that is given from a plaid request, there doesn't seem to be a name of account holder piece of the response unless I missed it. Can that be added to reduce fraud of someone using another persons bank information? i.e a daughter using her mothers bank information?

**Comment by ctrembl** [comment]
Hey Art -- Plaid does have the ability to pull in certain account holder information such as the name on file at the financial institution. To learn more about retrieving account holder information via the API, please email me directly at carl@plaid.com.
