### ISSUE TITLE
set_user isn't working

### ISSUE THREAD

**Issue by aesnyder** [plaid/plaid-ruby#68]
I'm sorry if this isn't the right place to post this but I've dug through the source and cannot understand why this isn't working: 

```
Plaid.set_user('test_boa', ['connect'], 'bofa')
```

I am getting `RuntimeError: It appears that the access token has been corrupted`

I have tried this with real users as well. Creating them works fine, I can verify their access token exists on the plaid website, but I get the same error.

Any suggestions would be welcomed.

**Comment by michaelckelly** [comment]
@aesnyder 

Sorry for the confusion - I think you're running into some logic that exists to support some deprecated behavior with our [API sandbox](https://plaid.com/docs#sandbox).

You'll only ever need to give two arguments to `Plaid.set_user`: an access token and a list of products (auth, connect, etc.):

```ruby
Plaid.config do |p|
    p.customer_id = 'test_id'
    p.secret = 'test_secret'
    p.environment_location = 'https://tartan.plaid.com'
end

# Initialize user with a sandbox access token
user = Plaid.set_user('test_bofa', ['connect'])
# Print the name of each account
user.accounts.each { |account| print account.meta['name'] + "\n"}
```

For tartan and production users, the access token will be a long string - the same code will work, though!

**Comment by aesnyder** [comment]
Thanks for the fast response, giving it a go now on version 1.5.2!

**Comment by aesnyder** [comment]
Okay, thanks again. This appears to work with the test access_token 'test_bofa'. 

Unfortunately when I use my access token I created from my own boa account I'm getting `request failed`. I did verify via the web interface that this exact token is available and has permissions for "connect". 

Any thoughts?

**Comment by aesnyder** [comment]
Ah tagged it down. Code 1215 on there -- mfa reset... Thanks for you help. Closing as the original answer was correct.

**Comment by michaelckelly** [comment]
@aesnyder 

Glad you got it figured out! We're working to improve the error handling/messaging in the ruby library as well (see https://github.com/plaid/plaid-ruby/pull/61). The library currently strips out some helpful information from the actual API response.
