### ISSUE TITLE
Questions about the upgrade and transactions methods in the users model

### ISSUE THREAD

**Issue by miguelperez** [plaid/plaid-ruby#70]
Hi Guys, I do not know if this is correct behaviour.
 
I add_user with auth scope. I want to get bank data, because then I will try to get transactions related to the accounts.

    user_auth = Plaid.add_user('auth', 'plaid_test', 'plaid_good', 'usaa', '1234')
    auth_data = user_auth.mfa_authentication('tomato')

Checking the user permissions seems right, the user only have access to the auth scope.

    user_auth.permit?('connect') # returns false
    user_auth.permit?('auth') # returns true

Based on the code, I see I can easily upgrade the user to fetch data related to the `connect` scope.

    user_auth.upgrade # or user_auth.upgrade('connect')

The thing is that using the gem, still the user has no permissions. So transaction data is empty.

    user_auth.permit?('connect') # returns false
    user_auth.permit?('auth') # returns true
    user_auth.transactions

The only way I could upgrade the user, and fetching his transactions was by using `Connection` manually.

    Plaid::Connection.post('upgrade', { access_token: user_auth.access_token, upgrade_to: 'connect' })

    payload = { access_token: user_auth.access_token }
    Plaid::Connection.post('connect/get', payload)

The reason I am doing this its because I want to be able of fetching all of users information in a background process, after the user signup.

Is this the correct behaviour? 

Thanks,

**Comment by ACPK** [comment]
@dmerrick ?

**Comment by a17levine** [comment]
@miguelperez I'm having the same problem. I don't think the 'connect' code works. Thanks for the workaround, I'll try that now

**Comment by be9** [comment]
@miguelperez @a17levine we've just released the 2.0.0.alpha version of the library which is a major overhaul. Eager to try it and check if the problem still exists?

**Comment by be9** [comment]
No feedback, closing.
