### ISSUE TITLE
Required to use in ruby ruby 1.9.3

### ISSUE THREAD

**Issue by nitesh-varma** [plaid/plaid-ruby#72]
Hi,

Needs to integrate Plaid with UI widget of https://github.com/plaid/link and 'Plaid' gem for internal operation of exchange_token.
 
But I had found that supported version of this gem (i.e 1.0.0) for ruby 1.9.3 does not have Plaid#exchange_token.

Please advise, any way so that I can use above gem with ruby 1.9.3.

Thanks,
Nitesh

**Comment by nitesh-varma** [comment]
Hi,

I had done modification for above and sent pull request at https://github.com/plaid/plaid-ruby/pull/73

Thanks,
Nitesh

**Comment by michaelckelly** [comment]
Closing - https://github.com/plaid/plaid-ruby/pull/73 was merged!
