### ISSUE TITLE
Need a lighter weight approach to response handling

### ISSUE THREAD

**Issue by l85m** [plaid/plaid-ruby#81]
The gem does not return the actual JSON response from plaid.  Instead it proscribes a certain approach to handling responses, especially transactions and errors.  This is adding complexity without any apparent advantages, and especially in the case of errors, requires reading the source code to map the responses defined in the Plaid API documentation to how this Gem handles them.  

Much better to just return the full response including the HTTP status and let people decide how they want to use it.  This is approach is lighter weight, more transparent, and more flexible.

**Comment by dam13n** [comment]
I agree.

**Comment by dmerrick** [comment]
Thank you for the suggestion! I see where you are coming from and I feel your pain.

This is something we will seriously consider for future versions of the gem.
