### ISSUE TITLE
Plaid.set_user with Auth and Connect returns 2 non-merged sets of accounts

### ISSUE THREAD

**Issue by augustj** [plaid/plaid-ruby#82]
plaid-ruby 1.6.0

When Plaid.set_user is called with multiple services, the accounts are not merged.
The accounts from each service are added to the user.  
<pre><code>Plaid.set_user('test_wells', ['auth']).accounts.each {|a| puts a.id}
QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK
nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy
XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo
pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k

Plaid.set_user('test_wells', ['connect']).accounts.each {|a| puts a.id}
QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK
nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy
XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo
pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k

Plaid.set_user('test_wells', ['connect', 'auth']).accounts.each {|a| puts a.id}
QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK
nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy
XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo
pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k
QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK
nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy
XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo
pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k</code></pre>

Looking at the code in User.rb on line 160, there is no way the merging could ever work.  The accounts.any? and accounts.find are both comparing accounts to account id's - apples to oranges.  I am also unclear on what owned_account.new(account) is trying to accomplish.

<pre><code>res['accounts'].each do |account|
  if self.accounts.any? { |h| h == account['_id'] }
    owned_account = self.accounts.find { |h| h == account['_id'] }
    owned_account.new(account)
  else
    self.accounts << Account.new(account)
  end
end if res['accounts']
</code></pre>

**Comment by dmerrick** [comment]
Thank you for reporting this. It has been fixed in https://github.com/plaid/plaid-ruby/pull/86.
