### ISSUE TITLE
delete_user for other products

### ISSUE THREAD

**Issue by mwean** [plaid/plaid-ruby#85]
Looking at the [code for `User#delete_user`](https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/models/user.rb#L53-L55), it looks like it would only work for the "info" product. Does that mean I have to upgrade the user to "info" before deleting them? Also, will that delete them across all products?

**Comment by dmerrick** [comment]
At this time, delete is not product-specific, so a DELETE request to /info would remove access too all products, and not just info.
