### ISSUE TITLE
Delete method not working

### ISSUE THREAD

**Issue by rubendinho** [plaid/plaid-ruby#95]
Are there issues deleting users in Plaid? I am using the delete_user() method on a user set with an active access token but the method doesn't seem to do anything and i'm able to use that access token to pull data without any issues. 

plaid_user=Plaid.set_user(token)
plaid_user.delete_user()

When i delete the same user via a simple curl request, it does get deleted. Has anyone used the delete_user method successfully?

Thank you
Ruben

**Comment by Deekor** [comment]
I just ran into the same issue. 

```
[44] pry(main)> user.delete_user
=> #<Net::HTTPUnauthorized 401 Unauthorized readbody=true>
```

Any update on this?

**Comment by rubendinho** [comment]
I was able to get this to work using:
Plaid::Connection.delete('connect', { access_token: token })
