### ISSUE TITLE
Is there a way to update a username and password?

### ISSUE THREAD

**Issue by Deekor** [plaid/plaid-ruby#97]
https://plaid.com/docs/#update-user

Any way to do this in the gem? I've been looking but haven't seen it yet and just want to be sure.

**Comment by be9** [comment]
It's definitely possible with 2.0.0.alpha and is as simple as:

```ruby
user = Plaid::User.load(:connect, 'access_token')
user.update('newusername', 'newpassword')
```

I hope this answers your question.
