### ISSUE TITLE
OmniAuth

### ISSUE THREAD

**Issue by dudo** [plaid/plaid-ruby#98]
Any thoughts on using your API with devise (via omniauth)? I've been dwelling on it, and I'd be open to suggestions on a strategy.

**Comment by be9** [comment]
@dudo could you describe a test case how would you use Plaid API along with Devise?

**Comment by dudo** [comment]
The idea would be to let them log in directly to the application implementing Plaid with their bank credentials. With an omniauth strategy in place, people could log into various financial apps with their bank's credentials. 

Seems like you folks are in a unique position to make that possible.

**Comment by charleswli** [comment]
Hi @dudo, thank you for the suggestion, but we currently don't have plans to officially provide an OmniAuth strategy. We will keep this in mind for the future though!
