### ISSUE TITLE
Duplicate transaction information?

### ISSUE THREAD

**Issue by ritec** [plaid/plaid-ruby#99]
I am not sure if this is your issue or if this is a bank specific issue but I seem to be getting duplicate transactions data when issuing the `user.get('connect')` call using Chase as the Bank. I tried to duplicate the problem with your tests using Wells Fargo as the bank but I did not get duplicate transactions this way. The data I get back from the call contains 2 copies of the same id for each transaction. 

Can anyone else confirm this problem?  
 Below is the code that returns the duplicate data.

    user = Plaid.set_user(access_token, ['connect'])
    user.get('connect')

**Comment by alexvbush** [comment]
having the same issue

**Comment by alexvbush** [comment]
seems like https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/models/user.rb#L160

```
def populate_user!(res)
      res['accounts'].each do |account|
        if self.accounts.none? { |h| h.id == account['_id'] }
          self.accounts << Account.new(account)
        end
      end if res['accounts']

      res['transactions'].each do |transaction|
        if self.transactions.any? { |t| t == transaction['_id'] }
          owned_transaction = self.transactions.find { |h| h == transaction['_id'] }
          owned_transaction.new(transaction)
        else
          self.transactions << Transaction.new(transaction)
        end
      end if res['transactions']

      self.pending_mfa_questions = {}
      self.information = Information.new(res['info']) if res['info']
      self.api_res = 'success'

      # TODO: Remove the following line when upgrading to V-2
      self.info.merge!(res['info']) if res['info']
      # End TODO

      self.access_token = res['access_token'].split[0]
      self.type = res['access_token'].split[1]
    end
```

is not identifying transactions correctly.

**Comment by alexvbush** [comment]
Also I noticed that `user.account[0].transactions` is actually `nil` for all accounts

**Comment by alexvbush** [comment]
going through the code it doesn't seem like transactions for accounts get populated anywhere during the parsing. (https://github.com/plaid/plaid-ruby/blob/master/lib/plaid/models/account.rb)
Is it a good candidate for a PR or you guys are working on it in V2?

**Comment by ritec** [comment]
Alex, thanks for confirming you are also having the issue. I also thought there was something wrong with populate_user, might look a bit more into it once I have some time.

**Comment by ldrbrandon** [comment]
I noticed I get duplicate accounts when using auth and upgrade but haven't noticed it with connect. I'd end up with a set of accounts that had no account/routing numbers and a set of accounts that did have them. I just filter out the accounts that don't have the account/routing numbers.

**Comment by be9** [comment]
@ldrbrandon @ritec @alexvbush can you check if this problem pertains to the 2.0.0.alpha version of the library which we've just released today?

**Comment by ritec** [comment]
@be9 I am pleased to inform you that with version 2.0 of the gem I am no longer getting duplicate transactions. Great Job! 👍

**Comment by be9** [comment]
Yay @ritec! Thanks for trying the alpha version! Closing this then.
